<x-admin-layout title="Courier Integration">
    <div x-data="{ addCourierOpen: @js($errors->any()) }" class="min-h-screen bg-slate-50 text-slate-900 dark:bg-[#111827] dark:text-slate-100">
        <div x-cloak x-show="menuOpen" @click="menuOpen = false" class="fixed inset-0 z-30 bg-slate-950/50 lg:hidden"></div>
        <x-admin-sidebar />

        <main class="min-w-0 lg:pl-72">
            <x-admin-topbar />

            <div class="mx-auto max-w-7xl p-5 sm:p-8">
                <div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
                    <div>
                        <p class="text-sm font-semibold text-indigo-600 dark:text-indigo-400">Delivery partners</p>
                        <h1 class="mt-1 text-2xl font-bold">Courier Integration</h1>
                        <p class="mt-2 text-sm text-slate-500 dark:text-slate-400">Connect courier accounts, verify API access and control which integration is active.</p>
                    </div>
                    <button type="button" @click="addCourierOpen = true" class="inline-flex items-center justify-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-indigo-500/20 transition hover:bg-indigo-700"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-width="2" d="M12 5v14M5 12h14"/></svg>Add New Courier</button>
                </div>

                @if (session('status'))<div class="mb-6 rounded-xl bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-700 dark:bg-emerald-500/15 dark:text-emerald-300">{{ session('status') }}</div>@endif
                @if (session('error'))<div class="mb-6 rounded-xl bg-rose-50 px-4 py-3 text-sm font-medium text-rose-700 dark:bg-rose-500/15 dark:text-rose-300">{{ session('error') }}</div>@endif

                <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-[#161f2e]">
                    <div class="border-b border-slate-200 p-5 dark:border-slate-800">
                        <h2 class="font-bold">Connected couriers</h2>
                        <p class="mt-1 text-xs text-slate-500">{{ $integrations->total() }} configured {{ Str::plural('integration', $integrations->total()) }}</p>
                    </div>

                    <div class="overflow-x-auto">
                        <table class="w-full min-w-[900px] text-left text-sm">
                            <thead class="bg-slate-50 text-xs uppercase tracking-wider text-slate-500 dark:bg-slate-800/60 dark:text-slate-400"><tr><th class="px-6 py-4">Courier</th><th class="px-6 py-4">API credentials</th><th class="px-6 py-4">Status</th><th class="px-6 py-4">Connection</th><th class="px-6 py-4">Last checked</th><th class="px-6 py-4 text-right">Actions</th></tr></thead>
                            <tbody class="divide-y divide-slate-100 dark:divide-slate-800">
                                @forelse ($integrations as $integration)
                                    <tr class="transition hover:bg-slate-50/70 dark:hover:bg-slate-800/30">
                                        <td class="px-6 py-4"><div class="flex items-center gap-3"><span class="grid h-12 w-16 shrink-0 place-items-center overflow-hidden rounded-xl border border-slate-200 bg-white p-1.5 dark:border-slate-700"><img src="{{ asset('images/couriers/'.match ($integration->provider) { 'pathao' => 'pathao.png', 'redx' => 'redx.jpg', 'paperfly' => 'paperfly.png', default => 'steadfast.jpg' }) }}" alt="{{ $integration->name }} logo" class="h-full w-full object-contain"></span><div><p class="font-semibold">{{ $integration->name }}</p><p class="mt-0.5 text-xs capitalize text-slate-500">{{ $integration->provider }}</p></div></div></td>
                                        <td class="px-6 py-4"><p class="font-mono text-xs text-slate-500">API Key: ••••••••</p><p class="mt-1 max-w-52 truncate text-xs text-slate-400" title="{{ $integration->base_url }}">{{ $integration->base_url }}</p></td>
                                        <td class="px-6 py-4">@if ($integration->is_active)<span class="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700 dark:bg-emerald-500/15 dark:text-emerald-300">Active</span>@else<span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-600 dark:bg-slate-800 dark:text-slate-300">Inactive</span>@endif</td>
                                        <td class="px-6 py-4">@if ($integration->last_test_succeeded === true)<span class="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700 dark:bg-emerald-500/15 dark:text-emerald-300">Connected</span>@elseif ($integration->last_test_succeeded === false)<span class="rounded-full bg-rose-50 px-2.5 py-1 text-xs font-semibold text-rose-700 dark:bg-rose-500/15 dark:text-rose-300" title="{{ $integration->last_error }}">Failed</span>@else<span class="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-semibold text-amber-700 dark:bg-amber-500/15 dark:text-amber-300">Not tested</span>@endif</td>
                                        <td class="px-6 py-4 text-slate-500 dark:text-slate-400">{{ $integration->last_tested_at?->diffForHumans() ?? 'Never' }}</td>
                                        <td class="px-6 py-4"><div class="flex items-center justify-end gap-2">@if ($integration->provider === 'steadfast')<form method="POST" action="{{ route('courier-integrations.test', $integration) }}">@csrf<button type="submit" class="rounded-lg bg-indigo-50 px-3 py-2 text-xs font-semibold text-indigo-700 transition hover:bg-indigo-100 dark:bg-indigo-500/15 dark:text-indigo-300">Test</button></form>@else<span class="rounded-lg bg-amber-50 px-3 py-2 text-xs font-semibold text-amber-700 dark:bg-amber-500/15 dark:text-amber-300">Client pending</span>@endif<form method="POST" action="{{ route('courier-integrations.toggle', $integration) }}">@csrf @method('PATCH')<button type="submit" class="rounded-lg bg-slate-100 px-3 py-2 text-xs font-semibold text-slate-700 transition hover:bg-slate-200 dark:bg-slate-800 dark:text-slate-300">{{ $integration->is_active ? 'Disable' : 'Enable' }}</button></form><form method="POST" action="{{ route('courier-integrations.destroy', $integration) }}" onsubmit="return confirm('Remove this courier integration?');">@csrf @method('DELETE')<button type="submit" class="rounded-lg bg-rose-50 px-3 py-2 text-xs font-semibold text-rose-700 transition hover:bg-rose-100 dark:bg-rose-500/15 dark:text-rose-300">Remove</button></form></div></td>
                                    </tr>
                                @empty
                                    <tr><td colspan="6" class="px-6 py-14 text-center"><p class="font-semibold">No courier connected yet.</p><p class="mt-1 text-sm text-slate-500">Add a courier provider to start configuring delivery.</p></td></tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>

                    @if ($integrations->hasPages())<div class="border-t border-slate-200 px-5 py-4 dark:border-slate-800">{{ $integrations->links() }}</div>@endif
                </section>
            </div>
        </main>

        <div x-cloak x-show="addCourierOpen" x-transition.opacity @keydown.escape.window="addCourierOpen = false" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4">
            <div role="dialog" aria-modal="true" aria-labelledby="add-courier-title" @click.outside="addCourierOpen = false" x-transition class="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-2xl border border-slate-200 bg-white shadow-2xl dark:border-slate-700 dark:bg-[#161f2e]">
                <div class="sticky top-0 z-10 flex items-center justify-between border-b border-indigo-100 bg-indigo-50 px-5 py-4 dark:border-indigo-500/20 dark:bg-indigo-500/10"><div><p class="text-xs font-semibold uppercase tracking-wider text-indigo-600 dark:text-indigo-400">API connection</p><h2 id="add-courier-title" class="mt-1 text-xl font-bold">Add New Courier</h2></div><button type="button" @click="addCourierOpen = false" class="rounded-lg p-2 text-slate-400 transition hover:bg-white hover:text-slate-700 dark:hover:bg-slate-800" aria-label="Close"><svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-width="2" d="m6 18 12-12M6 6l12 12"/></svg></button></div>

                <form method="POST" action="{{ route('courier-integrations.store') }}" x-data="{ provider: @js(old('provider', 'steadfast')), name: @js(old('name', 'Steadfast Courier')), baseUrl: @js(old('base_url', 'https://portal.packzy.com/api/v1')), providerChanged() { const providers = { steadfast: { name: 'Steadfast Courier', url: 'https://portal.packzy.com/api/v1' }, pathao: { name: 'Pathao Courier', url: '' }, redx: { name: 'RedX Courier', url: '' }, paperfly: { name: 'Paperfly Courier', url: '' } }; this.name = providers[this.provider].name; this.baseUrl = providers[this.provider].url } }">
                    @csrf
                    <div class="space-y-5 p-5 sm:p-7">
                        <fieldset><legend class="text-sm font-semibold">Courier provider</legend><div class="mt-2 grid grid-cols-2 gap-3"><label :class="provider === 'steadfast' ? 'border-indigo-500 bg-indigo-50 ring-1 ring-indigo-500 dark:bg-indigo-500/10' : 'border-slate-200 bg-white hover:border-indigo-300 dark:border-slate-700 dark:bg-slate-800'" class="cursor-pointer rounded-xl border p-3 transition"><input type="radio" name="provider" value="steadfast" x-model="provider" @change="providerChanged()" class="sr-only"><span class="flex h-12 items-center justify-center rounded-lg bg-white p-1"><img src="{{ asset('images/couriers/steadfast.jpg') }}" alt="Steadfast Courier logo" class="h-full w-full object-contain"></span><span class="mt-2 block text-center text-xs font-semibold">Steadfast</span></label><label :class="provider === 'pathao' ? 'border-indigo-500 bg-indigo-50 ring-1 ring-indigo-500 dark:bg-indigo-500/10' : 'border-slate-200 bg-white hover:border-indigo-300 dark:border-slate-700 dark:bg-slate-800'" class="cursor-pointer rounded-xl border p-3 transition"><input type="radio" name="provider" value="pathao" x-model="provider" @change="providerChanged()" class="sr-only"><span class="flex h-12 items-center justify-center rounded-lg bg-white p-1"><img src="{{ asset('images/couriers/pathao.png') }}" alt="Pathao Courier logo" class="h-full w-full object-contain"></span><span class="mt-2 block text-center text-xs font-semibold">Pathao</span></label><label :class="provider === 'redx' ? 'border-indigo-500 bg-indigo-50 ring-1 ring-indigo-500 dark:bg-indigo-500/10' : 'border-slate-200 bg-white hover:border-indigo-300 dark:border-slate-700 dark:bg-slate-800'" class="cursor-pointer rounded-xl border p-3 transition"><input type="radio" name="provider" value="redx" x-model="provider" @change="providerChanged()" class="sr-only"><span class="flex h-12 items-center justify-center rounded-lg bg-white p-1"><img src="{{ asset('images/couriers/redx.jpg') }}" alt="RedX Courier logo" class="h-full w-full object-contain"></span><span class="mt-2 block text-center text-xs font-semibold">RedX</span></label><label :class="provider === 'paperfly' ? 'border-indigo-500 bg-indigo-50 ring-1 ring-indigo-500 dark:bg-indigo-500/10' : 'border-slate-200 bg-white hover:border-indigo-300 dark:border-slate-700 dark:bg-slate-800'" class="cursor-pointer rounded-xl border p-3 transition"><input type="radio" name="provider" value="paperfly" x-model="provider" @change="providerChanged()" class="sr-only"><span class="flex h-12 items-center justify-center rounded-lg bg-white p-1"><img src="{{ asset('images/couriers/paperfly.png') }}" alt="Paperfly Courier logo" class="h-full w-full object-contain"></span><span class="mt-2 block text-center text-xs font-semibold">Paperfly</span></label></div>@error('provider')<p class="mt-2 text-xs text-rose-600">{{ $message }}</p>@enderror</fieldset>
                        <div><label for="name" class="text-sm font-semibold">Connection name</label><input id="name" name="name" x-model="name" required class="mt-2 w-full rounded-xl border-slate-300 bg-white px-3 py-2.5 text-sm dark:border-slate-700 dark:bg-slate-800" placeholder="Courier account name">@error('name')<p class="mt-2 text-xs text-rose-600">{{ $message }}</p>@enderror</div>
                        <div><label for="api_key" class="text-sm font-semibold">API Key</label><input id="api_key" name="api_key" type="password" value="{{ old('api_key') }}" required autocomplete="off" class="mt-2 w-full rounded-xl border-slate-300 bg-white px-3 py-2.5 font-mono text-sm dark:border-slate-700 dark:bg-slate-800">@error('api_key')<p class="mt-2 text-xs text-rose-600">{{ $message }}</p>@enderror</div>
                        <div><label for="secret_key" class="text-sm font-semibold">Secret Key</label><input id="secret_key" name="secret_key" type="password" value="{{ old('secret_key') }}" required autocomplete="new-password" class="mt-2 w-full rounded-xl border-slate-300 bg-white px-3 py-2.5 font-mono text-sm dark:border-slate-700 dark:bg-slate-800">@error('secret_key')<p class="mt-2 text-xs text-rose-600">{{ $message }}</p>@enderror</div>
                        <div><label for="base_url" class="text-sm font-semibold">API Base URL</label><input id="base_url" name="base_url" type="url" x-model="baseUrl" required class="mt-2 w-full rounded-xl border-slate-300 bg-white px-3 py-2.5 text-sm dark:border-slate-700 dark:bg-slate-800" :placeholder="provider === 'steadfast' ? 'https://portal.packzy.com/api/v1' : 'Enter the API URL supplied by the courier'">@error('base_url')<p class="mt-2 text-xs text-rose-600">{{ $message }}</p>@enderror</div>
                        <label class="flex items-start gap-3 rounded-xl bg-slate-50 p-4 dark:bg-slate-800/60"><input type="hidden" name="is_active" value="0"><input name="is_active" type="checkbox" value="1" @checked(old('is_active', '1') === '1') class="mt-0.5 rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"><span><span class="block text-sm font-semibold">Enable this integration</span><span class="mt-1 block text-xs text-slate-500">Credentials are encrypted before being stored.</span></span></label>
                    </div>
                    <div class="sticky bottom-0 flex justify-end gap-3 border-t border-slate-200 bg-white px-5 py-4 dark:border-slate-700 dark:bg-[#161f2e]"><button type="button" @click="addCourierOpen = false" class="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold dark:border-slate-700">Cancel</button><button type="submit" class="rounded-xl bg-indigo-600 px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-indigo-700">Save Courier</button></div>
                </form>
            </div>
        </div>
    </div>
</x-admin-layout>
