<header class="sticky top-0 z-20 flex h-20 items-center justify-between border-b border-slate-200 bg-slate-50/90 px-4 backdrop-blur dark:border-slate-800 dark:bg-[#111827]/90 sm:px-7 lg:px-10">
    <div class="flex items-center gap-3">
        <button @click="menuOpen = true" class="rounded-xl p-2 text-slate-600 dark:text-slate-300 lg:hidden" aria-label="Open menu"><svg class="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/></svg></button>
        <label class="hidden w-72 items-center gap-3 rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-slate-400 dark:border-slate-700 dark:bg-slate-800 sm:flex"><svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><circle cx="11" cy="11" r="7" stroke-width="2"/><path stroke-linecap="round" stroke-width="2" d="m20 20-4-4"/></svg><input class="w-full border-0 bg-transparent p-0 text-sm text-slate-700 placeholder:text-slate-400 focus:ring-0 dark:text-slate-200" placeholder="Search anything..." type="search"></label>
    </div>
    <div class="flex items-center gap-2 sm:gap-4">
        <button @click="toggleTheme()" :aria-label="darkMode ? 'Switch to light mode' : 'Switch to dark mode'" :title="darkMode ? 'Light mode' : 'Dark mode'" class="rounded-xl border border-slate-200 bg-white p-2.5 text-slate-500 transition hover:border-indigo-300 hover:text-indigo-600 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-400 dark:hover:border-indigo-500 dark:hover:text-indigo-400">
            <svg x-cloak x-show="darkMode" class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><circle cx="12" cy="12" r="4" stroke-width="2"/><path stroke-linecap="round" stroke-width="2" d="M12 2v2m0 16v2M4.9 4.9l1.4 1.4m11.4 11.4 1.4 1.4M2 12h2m16 0h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></svg>
            <svg x-cloak x-show="!darkMode" class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="M20.35 15.35A9 9 0 0 1 8.65 3.65a9 9 0 1 0 11.7 11.7Z"/></svg>
        </button>
        <div x-data="{ open: false, unreadCount: {{ $adminUnreadOrderCount ?? 0 }}, notifications: [], async refresh() { if (document.hidden) return; try { const response = await fetch('{{ route('orders.notifications') }}', { headers: { Accept: 'application/json' } }); if (response.ok) { const data = await response.json(); this.unreadCount = data.unread_count; this.notifications = data.orders; window.dispatchEvent(new CustomEvent('order-notifications-updated', { detail: { unreadCount: this.unreadCount } })); } } catch (error) {} }, init() { this.refresh(); setInterval(() => this.refresh(), 15000); document.addEventListener('visibilitychange', () => { if (!document.hidden) this.refresh() }) } }" @click.outside="open = false" @keydown.escape.window="open = false" class="relative">
            <button type="button" @click="open = !open; if (open) refresh()" class="relative rounded-xl p-2.5 text-slate-500 transition hover:bg-white hover:text-indigo-600 dark:text-slate-400 dark:hover:bg-slate-800" aria-label="Notifications" :aria-expanded="open"><svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-width="2" d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></svg><span x-cloak x-show="unreadCount > 0" class="absolute -right-1 -top-1 grid min-h-5 min-w-5 place-items-center rounded-full bg-rose-500 px-1 text-[10px] font-bold text-white ring-2 ring-slate-50 dark:ring-[#111827]" x-text="unreadCount > 99 ? '99+' : unreadCount"></span></button>
            <div x-cloak x-show="open" x-transition.origin.top.right class="absolute right-[-3.5rem] mt-3 w-[min(90vw,360px)] overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl dark:border-slate-700 dark:bg-[#161f2e] sm:right-0">
                <div class="flex items-center justify-between border-b border-slate-100 px-4 py-3 dark:border-slate-800"><div><h2 class="text-sm font-bold">Order notifications</h2><p class="mt-0.5 text-[11px] text-slate-500"><span x-text="unreadCount"></span> unread orders</p></div><a href="{{ route('orders.index') }}" class="text-xs font-semibold text-indigo-600 dark:text-indigo-400">View all</a></div>
                <div class="max-h-96 overflow-y-auto p-2"><template x-if="notifications.length === 0"><p class="px-3 py-10 text-center text-sm text-slate-500">No order notifications yet.</p></template><template x-for="notification in notifications" :key="notification.number"><a :href="notification.url" class="mb-1 flex gap-3 rounded-xl px-3 py-3 transition hover:bg-slate-50 dark:hover:bg-slate-800" :class="notification.unread ? 'bg-indigo-50/80 dark:bg-indigo-500/10' : ''"><span class="relative mt-0.5 grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-indigo-100 text-indigo-600 dark:bg-indigo-500/15 dark:text-indigo-300"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-width="1.8" d="M3 3h2l2 11h10l3-8H6m2 12h.01M17 18h.01"/></svg><span x-show="notification.unread" class="absolute -right-1 -top-1 h-2.5 w-2.5 rounded-full bg-rose-500 ring-2 ring-white dark:ring-[#161f2e]"></span></span><span class="min-w-0 flex-1"><span class="flex items-center justify-between gap-2"><strong class="text-xs" x-text="notification.number"></strong><small class="whitespace-nowrap text-[10px] text-slate-400" x-text="notification.time"></small></span><span class="mt-1 block truncate text-sm" x-text="notification.customer"></span><span class="mt-1 block text-xs font-semibold text-indigo-600 dark:text-indigo-400" x-text="'৳' + Number(notification.total).toLocaleString('en-BD', { minimumFractionDigits: 2 })"></span></span></a></template></div>
            </div>
        </div>
        <div x-data="{ profileOpen: false }" @click.outside="profileOpen = false" @keydown.escape.window="profileOpen = false" class="relative">
            <button type="button" @click="profileOpen = !profileOpen" :aria-expanded="profileOpen" aria-haspopup="menu" class="flex items-center gap-3 rounded-xl p-1.5 transition hover:bg-slate-100 dark:hover:bg-slate-800">
                <span class="hidden text-right sm:block"><span class="block max-w-40 truncate text-sm font-semibold">{{ Auth::user()->name }}</span><span class="block text-xs text-slate-500">Administrator</span></span>
                @if (Auth::user()->profile_image_path)<img src="{{ asset('storage/'.Auth::user()->profile_image_path) }}" alt="{{ Auth::user()->name }}" class="h-10 w-10 rounded-full object-cover">@else<span class="grid h-10 w-10 place-items-center rounded-full bg-gradient-to-br from-indigo-500 to-violet-600 text-sm font-bold text-white">{{ strtoupper(substr(Auth::user()->name, 0, 1)) }}</span>@endif
                <svg class="hidden h-4 w-4 text-slate-400 transition-transform sm:block" :class="profileOpen && 'rotate-180'" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m6 9 6 6 6-6"/></svg>
            </button>

            <div x-cloak x-show="profileOpen" x-transition.origin.top.right role="menu" class="absolute right-0 mt-3 w-72 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl dark:border-slate-700 dark:bg-[#161f2e]">
                <div class="border-b border-slate-100 bg-slate-50 px-4 py-4 dark:border-slate-800 dark:bg-slate-800/50">
                    <p class="truncate text-sm font-bold">{{ Auth::user()->name }}</p>
                    <p class="mt-1 truncate text-xs text-slate-500 dark:text-slate-400">{{ Auth::user()->email }}</p>
                </div>
                <div class="p-2">
                    <a href="{{ route('profile.edit') }}" role="menuitem" class="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium text-slate-700 transition hover:bg-indigo-50 hover:text-indigo-700 dark:text-slate-300 dark:hover:bg-indigo-500/15 dark:hover:text-indigo-300"><svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><circle cx="12" cy="8" r="4" stroke-width="2"/><path stroke-linecap="round" stroke-width="2" d="M4 21a8 8 0 0 1 16 0"/></svg>Profile</a>
                    <a href="{{ route('profile.edit') }}#password-security" role="menuitem" class="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium text-slate-700 transition hover:bg-indigo-50 hover:text-indigo-700 dark:text-slate-300 dark:hover:bg-indigo-500/15 dark:hover:text-indigo-300"><svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><rect x="5" y="10" width="14" height="11" rx="2" stroke-width="2"/><path stroke-linecap="round" stroke-width="2" d="M8 10V7a4 4 0 0 1 8 0v3"/></svg>Change password</a>
                </div>
                <form method="POST" action="{{ route('logout') }}" class="border-t border-slate-100 p-2 dark:border-slate-800">
                    @csrf
                    <button type="submit" role="menuitem" class="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-medium text-rose-600 transition hover:bg-rose-50 dark:text-rose-400 dark:hover:bg-rose-500/10"><svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 17l5-5-5-5m5 5H3m10-8h6a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2h-6"/></svg>Log out</button>
                </form>
            </div>
        </div>
    </div>
</header>
