@props(['type'])
@php($aiSettings = App\Models\WebsiteSetting::query()->first())
@if($aiSettings?->openai_enabled)
<section x-data="{loading:false,error:'',result:null,language:@js($aiSettings->openai_default_language ?: 'Bangla'),tone:@js($aiSettings->openai_default_tone ?: 'Professional'),length:'medium',
async generate(){this.loading=true;this.error='';this.result=null;const form=this.$root.closest('form');const topic=form.querySelector('[name=title]')?.value||'';if(!topic){this.error='Enter a title or topic first.';this.loading=false;return}
const context=form.querySelector('[name=short_description]')?.value||form.querySelector('[name=excerpt]')?.value||'';const keywords=form.querySelector('[name=focus_keyword]')?.value||'';
try{const response=await fetch(@js(route('ai-content.generate')),{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]').content},body:JSON.stringify({content_type:@js($type),topic,context,keywords,language:this.language,tone:this.tone,length:this.length})});const data=await response.json();if(!response.ok)throw new Error(data.message||Object.values(data.errors||{})[0]?.[0]||'Generation failed.');this.result=data.content}catch(e){this.error=e.message}finally{this.loading=false}},
setField(name,value){const el=this.$root.closest('form').querySelector('[name='+name+']');if(!el)return;el.value=value||'';el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}))},
apply(){this.setField('title',this.result.title?this.result.title:'');this.setField('excerpt',this.result?this.result.excerpt:'');this.setField('short_description',this.result?this.result.excerpt:'');this.setField('seo_title',this.result?this.result.seo_title:'');this.setField('meta_description',this.result?this.result.meta_description:'');this.setField('tags',this.result?this.result.tags.join(', '):'');const editor=@js($type)==='product'?window.productDescriptionEditor:window.blogContentEditor;if(editor)editor.setData(this.result.description||'');else this.setField('description',this.result.description);this.result=null}}" class="ds-card ds-card-body mb-6">
<div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-sm font-semibold text-indigo-600">OpenAI</p><h2 class="mt-1 text-lg font-bold">AI content generator</h2><p class="mt-1 text-sm text-slate-500">Enter the title first, choose options, and generate an editable draft.</p></div><button type="button" @click="generate()" :disabled="loading" class="ds-button-primary"><span x-text="loading?'Generating...':'Generate with AI'"></span></button></div>
<div class="mt-5 grid gap-4 sm:grid-cols-3"><select x-model="language" class="ds-select ds-control"><option>Bangla</option><option>English</option><option>Bangla and English</option></select><select x-model="tone" class="ds-select ds-control"><option>Professional</option><option>Friendly</option><option>Persuasive</option><option>Luxury</option><option>Simple</option></select><select x-model="length" class="ds-select ds-control"><option value="short">Short</option><option value="medium">Medium</option><option value="long">Long</option></select></div>
<p x-show="error" x-text="error" class="ds-error mt-4"></p>
<div x-cloak x-show="result" class="mt-5 rounded-xl border border-indigo-200 bg-indigo-50/50 p-4 dark:border-indigo-500/30 dark:bg-indigo-500/10"><h3 class="font-bold" x-text="result?.title"></h3><p class="mt-2 text-sm text-slate-600 dark:text-slate-300" x-text="result?.excerpt"></p><div class="mt-4 flex gap-3"><button type="button" @click="apply()" class="ds-button-primary">Apply to form</button><button type="button" @click="result=null" class="ds-button-secondary">Discard</button></div></div>
</section>
@endif
