@props(['category', 'depth' => 0])

<tr class="border-b border-slate-100 bg-white transition hover:bg-slate-50 dark:border-slate-800 dark:bg-[#161f2e] dark:hover:bg-slate-800/70">
    <td class="w-10 px-3 py-4"><input type="checkbox" class="rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"></td>
    <td class="w-14 px-2 py-3"><div class="grid h-10 w-10 place-items-center overflow-hidden rounded bg-slate-100 text-slate-400 dark:bg-slate-800">@if ($category->navigation_image_path ?: $category->thumbnail_path)<img src="{{ asset('storage/'.($category->navigation_image_path ?: $category->thumbnail_path)) }}" alt="" class="h-full w-full object-contain">@else<svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-width="2" d="M4 5h16v14H4zM4 16l4-4 3 3 2-2 3 3"/></svg>@endif</div></td>
    <td class="min-w-56 px-3 py-4"><a href="{{ route('catalog.show', $category->slug) }}" class="font-medium text-indigo-600 hover:underline dark:text-indigo-400" style="padding-left: {{ $depth * 1.4 }}rem">{{ str_repeat('— ', $depth) }}{{ $category->name }}</a></td>
    <td class="max-w-48 px-3 py-4 text-sm text-slate-500"><span class="line-clamp-2">{{ $category->description ? strip_tags($category->description) : '—' }}</span></td>
    <td class="min-w-40 px-3 py-4 text-sm text-slate-500">{{ $category->slug }}</td>
    <td class="w-16 px-3 py-4 text-center text-sm font-medium text-indigo-600 dark:text-indigo-400">0</td>
    <td class="w-32 px-3 py-4"><div class="flex items-center justify-end gap-2"><a href="{{ route('catalog.show', $category->slug) }}" title="View category" class="grid h-8 w-8 place-items-center rounded-full bg-slate-200 text-slate-700 transition hover:bg-blue-500 hover:text-white dark:bg-slate-700 dark:text-slate-200 dark:hover:bg-blue-500"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="2.5" stroke-width="2"/></svg></a><a href="{{ route('categories.edit', $category) }}" data-category-edit title="Edit category" class="grid h-8 w-8 place-items-center rounded-full bg-slate-200 text-slate-700 transition hover:bg-slate-300 dark:bg-slate-700 dark:text-slate-200 dark:hover:bg-slate-600"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-width="2" d="m4 20 4.2-1 9.6-9.6a2.1 2.1 0 0 0-3-3L5.2 16 4 20Z"/></svg></a><form method="POST" action="{{ route('categories.destroy', $category) }}" onsubmit="return confirm('Delete this category?');">@csrf @method('DELETE')<button type="submit" title="Delete category" class="grid h-8 w-8 place-items-center rounded-full bg-slate-200 text-slate-700 transition hover:bg-rose-500 hover:text-white dark:bg-slate-700 dark:text-slate-200"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-width="2" d="M6 7h12m-8 4v5m4-5v5M9 7l1-3h4l1 3m-8 0 1 13h8l1-13"/></svg></button></form></div></td>
</tr>

@foreach ($category->childrenRecursive as $child)
    <x-category-table-row :category="$child" :depth="$depth + 1" />
@endforeach
