<x-admin-layout title="File Manager">
<div class="ds-page" x-data="{ uploadOpen:false, uploadFiles:[], folderOpen:false, renaming:null, seoEditing:null, deleting:null }">
    <div x-cloak x-show="menuOpen" @click="menuOpen=false" class="fixed inset-0 z-30 bg-slate-950/50 lg:hidden"></div><x-admin-sidebar />
    <main class="min-w-0 lg:pl-72"><x-admin-topbar />
        <div class="mx-auto max-w-7xl p-5 sm:p-8">
            <div class="mb-6 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
                <div><p class="text-sm font-semibold text-indigo-600 dark:text-indigo-400">Assets</p><h1 class="mt-1 text-2xl font-bold">File Manager</h1><p class="mt-2 text-sm text-slate-500">Upload and organize website images, documents, videos and other assets.</p></div>
                <div class="flex flex-wrap gap-2"><button type="button" @click="folderOpen=true" class="ds-button-secondary">+ Create folder</button><button type="button" @click="uploadOpen=true" class="ds-button-primary">↑ Upload files</button></div>
            </div>
            @if(session('status'))<div class="mb-5 rounded-xl bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-700 dark:bg-emerald-500/15 dark:text-emerald-300">{{ session('status') }}</div>@endif
            @if($errors->any())<div class="mb-5 rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-700 dark:bg-rose-500/15 dark:text-rose-300"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

            <div class="mb-5 grid gap-4 sm:grid-cols-3">
                <div class="ds-card p-5"><p class="text-xs font-semibold uppercase tracking-wider text-slate-400">Current folder</p><p class="mt-2 truncate font-bold">{{ $path ?: 'All Files' }}</p></div>
                <div class="ds-card p-5"><p class="text-xs font-semibold uppercase tracking-wider text-slate-400">Total files</p><p class="mt-2 text-xl font-bold">{{ $totalFiles }}</p></div>
                <div class="ds-card p-5"><p class="text-xs font-semibold uppercase tracking-wider text-slate-400">Storage used</p><p class="mt-2 text-xl font-bold">{{ $totalSizeLabel }}</p></div>
            </div>

            <section class="ds-card overflow-hidden">
                <div class="flex flex-col gap-4 border-b border-slate-200 p-5 dark:border-slate-800 sm:flex-row sm:items-center sm:justify-between">
                    <nav class="flex min-w-0 flex-wrap items-center gap-1 text-sm" aria-label="Breadcrumb">@foreach($breadcrumbs as $crumb)<a href="{{ route('file-manager.index',array_filter(['path'=>$crumb['path']])) }}" class="rounded-lg px-2 py-1 font-medium {{ $loop->last?'text-slate-900 dark:text-white':'text-indigo-600 hover:bg-indigo-50 dark:text-indigo-400' }}">{{ $crumb['name'] }}</a>@if(!$loop->last)<span class="text-slate-300">/</span>@endif @endforeach</nav>
                    <form method="GET" action="{{ route('file-manager.index') }}" class="flex w-full gap-2 sm:w-auto">@if($path)<input type="hidden" name="path" value="{{ $path }}">@endif<label class="relative flex-1 sm:w-64"><span class="sr-only">Search files</span><svg class="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><circle cx="11" cy="11" r="7" stroke-width="2"/><path stroke-width="2" d="m20 20-4-4"/></svg><input name="search" value="{{ request('search') }}" placeholder="Search this folder..." class="ds-input ds-control pl-9"></label><button class="ds-button-secondary">Search</button></form>
                </div>

                @if($parentPath!==null)<div class="px-5 pt-5"><a href="{{ route('file-manager.index',array_filter(['path'=>$parentPath])) }}" class="inline-flex items-center gap-2 text-sm font-semibold text-indigo-600 dark:text-indigo-400">← Up one level</a></div>@endif

                <div class="grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
                    @foreach($folders as $folder)
                    <article class="group relative rounded-2xl border border-slate-200 bg-slate-50/70 p-4 transition hover:border-indigo-300 hover:bg-white dark:border-slate-700 dark:bg-slate-800/40 dark:hover:border-indigo-500/50">
                        <a href="{{ route('file-manager.index',['path'=>$folder['path']]) }}" class="block"><span class="grid h-12 w-12 place-items-center rounded-xl bg-amber-50 text-amber-500 dark:bg-amber-500/15"><svg class="h-7 w-7" fill="currentColor" viewBox="0 0 24 24"><path d="M3 6a2 2 0 0 1 2-2h5l2 2h7a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6Z"/></svg></span><h2 class="mt-4 truncate font-bold">{{ $folder['name'] }}</h2><p class="mt-1 text-xs text-slate-500">{{ $folder['item_count'] }} item(s)</p></a>
                        <div class="mt-4 flex gap-2 border-t border-slate-200 pt-3 dark:border-slate-700"><button type="button" @click="renaming={ path:@js($folder['path']), name:@js($folder['name']) }" class="text-xs font-semibold text-indigo-600">Rename</button><button type="button" @click="deleting={ path:@js($folder['path']), name:@js($folder['name']), type:'folder' }" class="ml-auto text-xs font-semibold text-rose-600">Delete</button></div>
                    </article>
                    @endforeach

                    @foreach($files as $file)
                    <article class="overflow-hidden rounded-2xl border border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-900">
                        <a href="{{ $file['is_image']?$file['url']:route('file-manager.download',['path'=>$file['path']]) }}" target="{{ $file['is_image']?'_blank':'_self' }}" class="grid h-40 overflow-hidden place-items-center bg-slate-100 p-3 dark:bg-slate-800">@if($file['is_image'])<img src="{{ $file['url'] }}" alt="{{ $file['name'] }}" loading="lazy" class="block h-full max-h-36 w-full max-w-full object-contain">@else<span class="rounded-xl bg-white px-4 py-3 text-sm font-black text-indigo-600 shadow-sm dark:bg-slate-900 dark:text-indigo-300">{{ $file['extension'] }}</span>@endif</a>
                        <div class="p-4"><div class="flex items-start gap-2"><h2 class="min-w-0 flex-1 truncate font-semibold" title="{{ $file['name'] }}">{{ $file['name'] }}</h2>@if($file['is_image'])<span class="shrink-0 rounded-full px-2 py-0.5 text-[10px] font-bold {{ $file['seo']['is_complete']?'bg-emerald-50 text-emerald-700 dark:bg-emerald-500/15 dark:text-emerald-300':'bg-amber-50 text-amber-700 dark:bg-amber-500/15 dark:text-amber-300' }}">{{ $file['seo']['is_complete']?'SEO Ready':'SEO Missing' }}</span>@endif</div><div class="mt-1 flex justify-between text-xs text-slate-500"><span>{{ $file['size_label'] }}</span><span>{{ date('d M Y',$file['modified_at']) }}</span></div><div class="mt-4 flex flex-wrap items-center gap-3 border-t border-slate-100 pt-3 dark:border-slate-800"><a href="{{ route('file-manager.download',['path'=>$file['path']]) }}" class="text-xs font-semibold text-emerald-600">Download</a>@if($file['is_image'])<button type="button" @click="seoEditing={ path:@js($file['path']), ...@js($file['seo']) }" class="text-xs font-semibold text-sky-600">SEO</button>@endif<button type="button" @click="renaming={ path:@js($file['path']), name:@js(pathinfo($file['name'],PATHINFO_FILENAME)) }" class="text-xs font-semibold text-indigo-600">Rename</button><button type="button" @click="deleting={ path:@js($file['path']), name:@js($file['name']), type:'file' }" class="ml-auto text-xs font-semibold text-rose-600">Delete</button></div></div>
                    </article>
                    @endforeach

                    @if($folders->isEmpty()&&$files->isEmpty())<div class="col-span-full py-16 text-center"><span class="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-slate-100 text-slate-400 dark:bg-slate-800"><svg class="h-8 w-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-width="1.5" d="M3 6h6l2 2h10v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6Z"/></svg></span><h2 class="mt-4 font-bold">This folder is empty</h2><p class="mt-1 text-sm text-slate-500">Upload files or create a folder to get started.</p></div>@endif
                </div>
            </section>
        </div>
    </main>

    <div x-cloak x-show="uploadOpen" x-transition.opacity @keydown.escape.window="uploadOpen=false" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div @click.outside="uploadOpen=false" class="ds-card w-full max-w-lg overflow-hidden shadow-2xl"><form method="POST" action="{{ route('file-manager.upload') }}" enctype="multipart/form-data">@csrf<input type="hidden" name="path" value="{{ $path }}"><div class="ds-card-header"><h2 class="ds-section-title">Upload files</h2><p class="ds-section-description">Up to 20 files, maximum 20 MB each.</p></div><div class="p-6"><label for="media-files" class="group flex min-h-48 cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed p-6 text-center transition" :class="uploadFiles.length ? 'border-indigo-400 bg-indigo-50/60 dark:border-indigo-500 dark:bg-indigo-500/10' : 'border-slate-300 hover:border-indigo-400 hover:bg-slate-50 dark:border-slate-700 dark:hover:bg-slate-800/50'"><span class="grid h-12 w-12 place-items-center rounded-2xl bg-indigo-50 text-indigo-600 transition group-hover:scale-105 dark:bg-indigo-500/15 dark:text-indigo-300"><svg class="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-width="1.8" d="M12 16V4m0 0L7 9m5-5 5 5M5 20h14"/></svg></span><span class="mt-4 text-sm font-bold" x-text="uploadFiles.length ? uploadFiles.length + (uploadFiles.length === 1 ? ' file selected' : ' files selected') : 'Drop files here or browse'"></span><span class="mt-1 text-xs text-slate-500">Images, documents, archives, audio and video</span><span class="mt-4 inline-flex items-center rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-700 shadow-sm transition group-hover:border-indigo-300 group-hover:text-indigo-600 dark:border-slate-600 dark:bg-slate-800 dark:text-slate-200">Browse files</span><span x-show="uploadFiles.length" class="mt-3 max-w-full text-xs text-slate-500" x-text="uploadFiles.slice(0, 3).map(file => file.name).join(', ') + (uploadFiles.length > 3 ? ' +' + (uploadFiles.length - 3) + ' more' : '')"></span><input id="media-files" type="file" name="files[]" multiple required class="sr-only" @change="uploadFiles = Array.from($event.target.files)"></label></div><div class="flex justify-end gap-2 border-t border-slate-200 px-6 py-4 dark:border-slate-700"><button type="button" @click="uploadOpen=false; uploadFiles=[]" class="ds-button-secondary">Cancel</button><button class="ds-button-primary" :disabled="!uploadFiles.length" :class="{ 'cursor-not-allowed opacity-50': !uploadFiles.length }">Upload</button></div></form></div></div>
    <div x-cloak x-show="folderOpen" x-transition.opacity @keydown.escape.window="folderOpen=false" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div @click.outside="folderOpen=false" class="ds-card w-full max-w-md overflow-hidden shadow-2xl"><form method="POST" action="{{ route('file-manager.folders.store') }}">@csrf<input type="hidden" name="path" value="{{ $path }}"><div class="ds-card-header"><h2 class="ds-section-title">Create folder</h2></div><div class="p-6"><label for="folder-name" class="ds-field-label">Folder name</label><input id="folder-name" name="name" required maxlength="100" class="ds-input ds-control" placeholder="e.g. Product images"></div><div class="flex justify-end gap-2 border-t border-slate-200 px-6 py-4 dark:border-slate-700"><button type="button" @click="folderOpen=false" class="ds-button-secondary">Cancel</button><button class="ds-button-primary">Create</button></div></form></div></div>
    <div x-cloak x-show="renaming" x-transition.opacity @keydown.escape.window="renaming=null" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div @click.outside="renaming=null" class="ds-card w-full max-w-md overflow-hidden shadow-2xl"><form data-ds-dirty-submit method="POST" action="{{ route('file-manager.items.rename') }}">@csrf @method('PATCH')<input type="hidden" name="path" :value="renaming?.path"><div class="ds-card-header"><h2 class="ds-section-title">Rename item</h2></div><div class="p-6"><label for="rename-name" class="ds-field-label">New name</label><input id="rename-name" name="name" x-model="renaming.name" required maxlength="150" class="ds-input ds-control"><p class="mt-2 text-xs text-slate-500">File extensions are preserved automatically.</p></div><div class="flex justify-end gap-2 border-t border-slate-200 px-6 py-4 dark:border-slate-700"><button type="button" @click="renaming=null" class="ds-button-secondary">Cancel</button><button class="ds-button-primary">Rename</button></div></form></div></div>
    <div x-cloak x-show="seoEditing" x-transition.opacity @keydown.escape.window="seoEditing=null" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div @click.outside="seoEditing=null" class="ds-card max-h-[92vh] w-full max-w-2xl overflow-y-auto shadow-2xl"><form data-ds-dirty-submit method="POST" action="{{ route('file-manager.images.seo') }}">@csrf @method('PATCH')<input type="hidden" name="path" :value="seoEditing?.path"><div class="ds-card-header"><h2 class="ds-section-title">Image SEO</h2><p class="ds-section-description">Use a descriptive filename and explain what the image shows.</p></div><div class="grid gap-5 p-6 sm:grid-cols-2"><div class="sm:col-span-2"><label for="seo-filename" class="ds-field-label">SEO filename</label><div class="flex items-center"><input id="seo-filename" name="filename" x-model="seoEditing.filename" required maxlength="100" class="ds-input ds-control"><span class="ml-2 text-sm text-slate-400">extension preserved</span></div><p class="mt-1 text-xs text-slate-500">Example: mens-black-leather-wallet</p></div><div class="sm:col-span-2"><div class="ds-field-header"><label for="seo-alt" class="ds-field-label">Alt text</label><span class="text-xs text-slate-400"><span x-text="seoEditing?.alt_text?.length||0"></span>/125</span></div><input id="seo-alt" name="alt_text" x-model="seoEditing.alt_text" required maxlength="125" class="ds-input ds-control" placeholder="Describe what is visible in the image"><p class="mt-1 text-xs text-slate-500">Keep it natural and specific; avoid keyword stuffing.</p></div><div><label for="seo-title" class="ds-field-label">Image title</label><input id="seo-title" name="title" x-model="seoEditing.title" maxlength="160" class="ds-input ds-control"></div><div><label for="seo-caption" class="ds-field-label">Caption</label><input id="seo-caption" name="caption" x-model="seoEditing.caption" maxlength="255" class="ds-input ds-control"></div><div class="sm:col-span-2"><label for="seo-description" class="ds-field-label">Description</label><textarea id="seo-description" name="description" x-model="seoEditing.description" rows="4" maxlength="1000" class="ds-textarea ds-control"></textarea></div></div><div class="flex justify-end gap-2 border-t border-slate-200 px-6 py-4 dark:border-slate-700"><button type="button" @click="seoEditing=null" class="ds-button-secondary">Cancel</button><button class="ds-button-primary">Save image SEO</button></div></form></div></div>
    <div x-cloak x-show="deleting" x-transition.opacity @keydown.escape.window="deleting=null" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div role="dialog" aria-modal="true" aria-labelledby="delete-item-title" @click.outside="deleting=null" class="ds-card w-full max-w-md overflow-hidden shadow-2xl"><form method="POST" action="{{ route('file-manager.items.destroy') }}">@csrf @method('DELETE')<input type="hidden" name="path" :value="deleting?.path"><div class="p-6 text-center"><span class="mx-auto grid h-14 w-14 place-items-center rounded-full bg-rose-50 text-rose-600 dark:bg-rose-500/15 dark:text-rose-300"><svg class="h-7 w-7" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-width="1.8" d="M6 7h12m-8 4v5m4-5v5M9 7l1-3h4l1 3m-8 0 1 13h8l1-13"/></svg></span><h2 id="delete-item-title" class="mt-4 text-xl font-bold">Delete <span x-text="deleting?.type"></span>?</h2><p class="mt-2 text-sm leading-6 text-slate-500">You are about to permanently delete <strong class="break-all text-slate-700 dark:text-slate-200" x-text="deleting?.name"></strong>.</p><p x-show="deleting?.type==='folder'" class="mt-2 text-sm font-medium text-rose-600">Everything inside this folder will also be deleted.</p></div><div class="flex justify-center gap-3 border-t border-slate-200 bg-slate-50/70 px-6 py-4 dark:border-slate-700 dark:bg-slate-800/40"><button type="button" @click="deleting=null" class="ds-button-secondary">Cancel</button><button type="submit" class="ds-button-danger">Yes, delete</button></div></form></div></div>
</div>
</x-admin-layout>
