<x-admin-layout title="View Customer">
    <div class="ds-page"><div x-cloak x-show="menuOpen" @click="menuOpen=false" class="fixed inset-0 z-30 bg-slate-950/50 lg:hidden"></div><x-admin-sidebar />
        <main class="min-w-0 lg:pl-72"><x-admin-topbar /><div class="mx-auto max-w-4xl p-5 sm:p-8">
            <a href="{{ route('customers.index') }}" class="text-sm font-semibold text-indigo-600">&larr; Back to customers</a>
            <section class="ds-card mt-5 overflow-hidden"><div class="border-b border-indigo-100 bg-indigo-50 px-6 py-7 dark:border-indigo-500/20 dark:bg-indigo-500/10"><div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div class="flex items-center gap-4"><div class="grid h-16 w-16 place-items-center rounded-2xl bg-indigo-600 text-2xl font-bold text-white">{{ strtoupper(substr($customer->name, 0, 1)) }}</div><div><p class="text-xs font-semibold uppercase tracking-wider text-indigo-600">Customer account</p><h1 class="mt-1 text-2xl font-bold">{{ $customer->name }}</h1><p class="mt-1 text-sm text-slate-500">{{ $customer->email }}</p></div></div><a href="{{ route('customers.edit', $customer) }}" class="ds-button-primary">Edit customer</a></div></div>
                <div class="grid gap-5 p-6 sm:grid-cols-3"><div><p class="text-xs text-slate-500">Email status</p><p class="mt-1 font-semibold">{{ $customer->email_verified_at ? 'Verified' : 'Pending' }}</p></div><div><p class="text-xs text-slate-500">Total purchases</p><p class="mt-1 font-semibold">{{ $purchaseCount }}</p></div><div><p class="text-xs text-slate-500">Joined</p><p class="mt-1 font-semibold">{{ $customer->created_at->format('M d, Y') }}</p></div></div>
            </section>
            <section class="ds-card mt-5 overflow-hidden"><div class="ds-card-header"><h2 class="ds-section-title">Recent purchases</h2></div><div class="divide-y divide-slate-100 dark:divide-slate-800">@forelse($recentOrders as $order)<a href="{{ route('orders.show', $order) }}" class="flex items-center justify-between gap-4 px-6 py-4 hover:bg-slate-50 dark:hover:bg-slate-800/40"><div><p class="font-semibold">{{ $order->order_number }}</p><p class="mt-1 text-xs text-slate-500">{{ $order->created_at->format('M d, Y · h:i A') }}</p></div><div class="text-right"><p class="font-bold">৳{{ number_format($order->total, 2) }}</p><p class="mt-1 text-xs capitalize text-slate-500">{{ $order->status }}</p></div></a>@empty<p class="px-6 py-10 text-center text-sm text-slate-500">No purchase history.</p>@endforelse</div></section>
        </div></main>
    </div>
</x-admin-layout>
