<div>
    <!-- When there is no desire, all things are at peace. - Laozi -->
</div>
<x-admin-layout title="Notice Board"><div x-data="{open:@js($errors->any()),edit:null,remove:null}" class="min-h-screen bg-slate-50 dark:bg-[#111827] dark:text-slate-100"><x-admin-sidebar/><main class="min-w-0 lg:pl-72"><x-admin-topbar/><div class="mx-auto max-w-7xl p-5 sm:p-8"><div class="mb-6 flex items-end justify-between"><div><p class="text-sm font-semibold text-indigo-600">Communication</p><h1 class="text-2xl font-bold">Notice board</h1><p class="mt-2 text-sm text-slate-500">Prepare and manage notices for selected audiences.</p></div><button @click="edit=null;open=true" class="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">+ Add notice</button></div>
@if(session('status'))<div class="mb-5 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">{{session('status')}}</div>@endif @if($errors->any())<div class="mb-5 rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{{$errors->first()}}</div>@endif
<div class="overflow-hidden rounded-2xl border bg-white dark:border-slate-800 dark:bg-[#161f2e]"><table class="w-full min-w-[700px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-slate-800"><tr><th class="px-6 py-4">Notice</th><th class="px-6 py-4">Publish to</th><th class="px-6 py-4">Status</th><th class="px-6 py-4 text-right">Actions</th></tr></thead><tbody class="divide-y">@forelse($notices as $notice)<tr><td class="px-6 py-4"><p class="font-semibold">{{$notice->name}}</p><p class="mt-1 max-w-xl truncate text-xs text-slate-500">{{$notice->details}}</p></td><td class="px-6 py-4">{{implode(', ',array_map('ucfirst',$notice->publish_to))}}</td><td class="px-6 py-4">{{$notice->is_active?'Active':'Inactive'}}</td><td class="px-6 py-4"><div class="flex justify-end gap-2"><button @click='edit=@json($notice);open=true' class="rounded-lg bg-indigo-50 px-3 py-2 text-xs font-semibold text-indigo-700">Edit</button><button @click="remove={{$notice->id}}" class="rounded-lg bg-rose-50 px-3 py-2 text-xs font-semibold text-rose-700">Delete</button></div></td></tr>@empty<tr><td colspan="4" class="p-14 text-center text-slate-500">No notice created yet.</td></tr>@endforelse</tbody></table>@if($notices->hasPages())<div class="border-t p-4">{{$notices->links()}}</div>@endif</div></div></main>
<div x-cloak x-show="open" class="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><div class="w-full max-w-xl rounded-2xl bg-white dark:bg-[#161f2e]"><div class="flex justify-between border-b p-5"><h2 class="text-xl font-bold" x-text="edit?'Edit notice':'Add notice'"></h2><button @click="open=false">✕</button></div><form method="POST" :action="edit?'{{url('/communication/notices')}}/'+edit.id:'{{route('communication.notices.store')}}'">@csrf<input x-show="edit" type="hidden" name="_method" value="PUT"><div class="space-y-4 p-5"><label class="block text-sm font-semibold">Notice name<input name="name" required :value="edit?.name||''" class="mt-2 w-full rounded-xl border-slate-300 dark:bg-slate-800"></label><label class="block text-sm font-semibold">Details<textarea name="details" required rows="6" x-text="edit?.details||''" class="mt-2 w-full rounded-xl border-slate-300 dark:bg-slate-800"></textarea></label><fieldset><legend class="text-sm font-semibold">Publish to</legend><div class="mt-2 flex flex-wrap gap-4">@foreach(['dashboard','customers','storefront'] as $place)<label class="flex gap-2 text-sm"><input type="checkbox" name="publish_to[]" value="{{$place}}" :checked="edit?.publish_to?.includes('{{$place}}')">{{ucfirst($place)}}</label>@endforeach</div></fieldset><label class="flex gap-2 text-sm"><input type="checkbox" name="is_active" value="1" :checked="edit?.is_active??true"> Active</label></div><div class="flex justify-end gap-3 border-t p-5"><button type="button" @click="open=false" class="rounded-xl border px-4 py-2">Cancel</button><button class="rounded-xl bg-indigo-600 px-5 py-2 text-white">Save notice</button></div></form></div></div>
<div x-cloak x-show="remove" class="fixed inset-0 z-[60] grid place-items-center bg-slate-950/50 p-4"><form method="POST" :action="'{{url('/communication/notices')}}/'+remove" class="w-full max-w-sm rounded-2xl bg-white p-6 dark:bg-[#161f2e]">@csrf @method('DELETE')<h3 class="text-lg font-bold">Delete this notice?</h3><div class="mt-5 flex justify-end gap-3"><button type="button" @click="remove=null" class="rounded-xl border px-4 py-2">Cancel</button><button class="rounded-xl bg-rose-600 px-4 py-2 text-white">Delete</button></div></form></div>
</div></x-admin-layout>
