<div>
    <!-- Simplicity is the essence of happiness. - Cedric Bledsoe -->
</div>
<x-admin-layout :title="ucfirst($channel).' Providers'">
<div x-data="{ modal: @js($errors->any()), edit: null, remove: null }" class="min-h-screen bg-slate-50 dark:bg-[#111827] dark:text-slate-100">
<x-admin-sidebar/><main class="min-w-0 lg:pl-72"><x-admin-topbar/>
<div class="mx-auto max-w-7xl p-5 sm:p-8">
<div class="mb-6 flex items-end justify-between gap-4"><div><p class="text-sm font-semibold text-indigo-600">Communication</p><h1 class="mt-1 text-2xl font-bold">{{ ucfirst($channel) }} providers</h1><p class="mt-2 text-sm text-slate-500">Configure, test and activate the provider used to send {{ $channel }} messages.</p></div><button @click="edit=null; modal=true" class="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">+ Add provider</button></div>
@if(session('status'))<div class="mb-5 rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{{ session('status') }}</div>@endif
@if(session('error'))<div class="mb-5 rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-700">{{ session('error') }}</div>@endif
@if($errors->any())<div class="mb-5 rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-700">{{ $errors->first() }}</div>@endif
<section class="overflow-hidden rounded-2xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-[#161f2e]"><div class="border-b border-slate-200 p-5 dark:border-slate-800"><h2 class="font-bold">Connected providers</h2><p class="mt-1 text-xs text-slate-500">{{ $providers->total() }} provider(s)</p></div>
<div class="overflow-x-auto"><table class="w-full min-w-[820px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-slate-800/60"><tr><th class="px-6 py-4">Provider</th><th class="px-6 py-4">Configuration</th><th class="px-6 py-4">Status</th><th class="px-6 py-4 text-right">Actions</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">
@forelse($providers as $provider)<tr class="hover:bg-slate-50/70 dark:hover:bg-slate-800/30"><td class="px-6 py-4"><p class="font-semibold">{{ $provider->name }}</p><p class="text-xs uppercase text-slate-500">{{ $provider->driver }}</p></td><td class="px-6 py-4 text-slate-500">{{ $channel==='email' ? ($provider->settings['host'] ?? 'Not configured') : ($provider->settings['url'] ?? 'Not configured') }}<p class="mt-1 text-xs">Secret: ••••••••</p></td><td class="px-6 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $provider->is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600' }}">{{ $provider->is_active ? 'Active' : 'Inactive' }}</span></td><td class="px-6 py-4"><div class="flex justify-end gap-2">
<button @click='edit=@json(["id"=>$provider->id,"name"=>$provider->name,"settings"=>collect($provider->settings)->except(["password","api_key"])]); modal=true' class="rounded-lg bg-indigo-50 px-3 py-2 text-xs font-semibold text-indigo-700">Edit</button>
<form method="POST" action="{{ route('communication.providers.toggle', [$channel,$provider]) }}">@csrf @method('PATCH')<button class="rounded-lg bg-slate-100 px-3 py-2 text-xs font-semibold">{{ $provider->is_active?'Disable':'Enable' }}</button></form>
<form method="POST" action="{{ route('communication.providers.test', [$channel,$provider]) }}" class="flex gap-1">@csrf<input required name="test_recipient" placeholder="{{ $channel==='email'?'name@example.com':'01XXXXXXXXX' }}" class="w-40 rounded-lg border-slate-300 px-2 py-1 text-xs dark:bg-slate-800"><button class="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-700">Test</button></form>
<button @click="remove={{ $provider->id }}" class="rounded-lg bg-rose-50 px-3 py-2 text-xs font-semibold text-rose-700">Delete</button></div></td></tr>
@empty<tr><td colspan="4" class="px-6 py-14 text-center text-slate-500">No provider added yet.</td></tr>@endforelse</tbody></table></div>@if($providers->hasPages())<div class="border-t p-4">{{ $providers->links() }}</div>@endif</section>
</div></main>
<div x-cloak x-show="modal" class="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><div @click.outside="modal=false" class="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white shadow-2xl dark:bg-[#161f2e]"><div class="flex items-center justify-between border-b p-5"><h2 class="text-xl font-bold" x-text="edit ? 'Edit provider' : 'Add provider'"></h2><button @click="modal=false">✕</button></div>
<form method="POST" :action="edit ? '{{ url('/communication/providers/'.$channel) }}/'+edit.id : '{{ route('communication.providers.store',$channel) }}'">@csrf<input x-show="edit" type="hidden" name="_method" value="PUT"><input type="hidden" name="driver" value="{{ $channel==='email'?'smtp':'http' }}"><div class="grid gap-4 p-5 sm:grid-cols-2">
<label class="sm:col-span-2 text-sm font-semibold">Provider name<input name="name" required :value="edit?.name||''" class="mt-2 w-full rounded-xl border-slate-300 dark:bg-slate-800"></label>
@if($channel==='email')
@foreach([['host','SMTP host','smtp.example.com'],['port','Port','587'],['username','Username','account@example.com'],['password','Password','Saved value will remain'],['from_address','Sender email','store@example.com'],['from_name','Sender name','Your Store']] as [$key,$label,$placeholder])<label class="text-sm font-semibold">{{ $label }}<input name="{{ $key }}" {{ in_array($key,['host','port','from_address','from_name'])?'required':'' }} type="{{ $key==='password'?'password':($key==='port'?'number':'text') }}" :value="edit?.settings?.{{ $key }}||''" placeholder="{{ $placeholder }}" class="mt-2 w-full rounded-xl border-slate-300 dark:bg-slate-800"></label>@endforeach
<label class="text-sm font-semibold">Encryption<select name="encryption" class="mt-2 w-full rounded-xl border-slate-300 dark:bg-slate-800"><option value="tls">TLS</option><option value="ssl">SSL</option><option value="none">None</option></select></label>
@else
@foreach([['url','API URL','https://sms.example.com/send'],['api_key','API key','Saved value will remain'],['sender_id','Sender ID','YourStore'],['to_parameter','Receiver parameter','to'],['message_parameter','Message parameter','message'],['api_key_parameter','API key parameter','api_key']] as [$key,$label,$placeholder])<label class="{{ $key==='url'?'sm:col-span-2':'' }} text-sm font-semibold">{{ $label }}<input name="{{ $key }}" {{ in_array($key,['url','to_parameter','message_parameter'])?'required':'' }} type="{{ $key==='api_key'?'password':($key==='url'?'url':'text') }}" :value="edit?.settings?.{{ $key }}||''" placeholder="{{ $placeholder }}" class="mt-2 w-full rounded-xl border-slate-300 dark:bg-slate-800"></label>@endforeach
@endif</div><div class="flex justify-end gap-3 border-t p-5"><button type="button" @click="modal=false" class="rounded-xl border px-4 py-2.5 text-sm font-semibold">Cancel</button><button class="rounded-xl bg-indigo-600 px-5 py-2.5 text-sm font-semibold text-white">Save provider</button></div></form></div></div>
<div x-cloak x-show="remove" class="fixed inset-0 z-[60] grid place-items-center bg-slate-950/50 p-4"><div class="w-full max-w-sm rounded-2xl bg-white p-6 dark:bg-[#161f2e]"><h3 class="text-lg font-bold">Delete provider?</h3><p class="mt-2 text-sm text-slate-500">This connection will be removed permanently.</p><form method="POST" :action="'{{ url('/communication/providers/'.$channel) }}/'+remove" class="mt-5 flex justify-end gap-3">@csrf @method('DELETE')<button type="button" @click="remove=null" class="rounded-xl border px-4 py-2">Cancel</button><button class="rounded-xl bg-rose-600 px-4 py-2 text-white">Delete</button></form></div></div>
</div></x-admin-layout>
