<x-admin-layout :title="ucfirst($channel).' Templates'">
<div x-data="{ open: false, edit: null }" class="min-h-screen bg-slate-50 dark:bg-[#111827] dark:text-slate-100"><x-admin-sidebar/><main class="min-w-0 lg:pl-72"><x-admin-topbar/>
<div class="w-full p-5 sm:p-7">
    <div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold text-indigo-600">Communication</p><h1 class="mt-1 text-2xl font-bold">{{ ucfirst($channel) }} templates</h1><p class="mt-2 text-sm text-slate-500">Manage reusable content, triggers and delivery status.</p></div><button @click="edit=null;open=true" class="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">+ Add template</button></div>
    @if(session('status'))<div class="mb-5 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">{{session('status')}}</div>@endif
    <div class="mb-5 flex flex-wrap gap-2">@foreach([''=>'All','transactional'=>'Transactional','marketing'=>'Marketing','automation'=>'Automation'] as $value=>$label)<a href="{{ route('communication.templates.index', [$channel, 'category'=>$value]) }}" class="rounded-xl px-4 py-2 text-sm font-semibold {{ $category===$value ? 'bg-indigo-600 text-white' : 'bg-white text-slate-600 hover:bg-indigo-50 dark:bg-slate-800 dark:text-slate-300' }}">{{ $label }}</a>@endforeach</div>
    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-[#161f2e]"><div class="overflow-x-auto"><table class="w-full min-w-[900px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-slate-800"><tr><th class="px-5 py-4">Template</th><th class="px-5 py-4">Category</th><th class="px-5 py-4">Trigger</th><th class="px-5 py-4">Status</th><th class="px-5 py-4 text-right">Actions</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">
    @forelse($templates as $template)<tr class="hover:bg-slate-50/70 dark:hover:bg-slate-800/30"><td class="px-5 py-4"><p class="font-semibold">{{$template->name}}</p><p class="mt-1 max-w-md truncate text-xs text-slate-500">{{$template->subject}}</p></td><td class="px-5 py-4"><span class="rounded-full bg-indigo-50 px-2.5 py-1 text-xs font-semibold capitalize text-indigo-700">{{$template->category}}</span></td><td class="px-5 py-4 text-xs text-slate-500">{{$template->trigger ?: 'Manual campaign'}}</td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{$template->is_active?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'}}">{{$template->is_active?'Enabled':'Disabled'}}</span></td><td class="px-5 py-4"><div class="flex justify-end gap-2"><form method="POST" action="{{route('communication.templates.toggle',[$channel,$template])}}">@csrf @method('PATCH')<button class="rounded-lg bg-slate-100 px-3 py-2 text-xs font-semibold">{{$template->is_active?'Disable':'Enable'}}</button></form><button @click="edit={{ Illuminate\Support\Js::from($template->only(['id','name','subject','body','category','preview_text','button_text','button_url','is_important','is_active'])) }};open=true" class="rounded-lg bg-indigo-50 px-3 py-2 text-xs font-semibold text-indigo-700">Edit</button></div></td></tr>
    @empty<tr><td colspan="5" class="p-14 text-center text-slate-500">No templates found.</td></tr>@endforelse</tbody></table></div><div class="border-t p-4">{{$templates->links()}}</div></section>
</div></main>
<div x-cloak x-show="open" class="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><div @click.outside="open=false" class="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white dark:bg-[#161f2e]"><div class="flex justify-between border-b p-5"><h2 class="text-xl font-bold" x-text="edit?'Edit template':'Add template'"></h2><button @click="open=false">×</button></div><form method="POST" :action="edit?'{{url('/communication/templates/'.$channel)}}/'+edit.id:'{{route('communication.templates.store',$channel)}}'">@csrf<input :disabled="!edit" type="hidden" name="_method" value="PUT"><div class="grid gap-4 p-5 sm:grid-cols-2"><label class="text-sm font-semibold">Name<input name="name" required :value="edit?.name||''" class="mt-2 w-full rounded-xl border-slate-300 dark:bg-slate-800"></label><label class="text-sm font-semibold">Category<select name="category" class="mt-2 w-full rounded-xl border-slate-300 dark:bg-slate-800"><option>transactional</option><option>marketing</option><option>automation</option></select></label>@if($channel==='email')<label class="sm:col-span-2 text-sm font-semibold">Subject<input name="subject" required :value="edit?.subject||''" class="mt-2 w-full rounded-xl border-slate-300 dark:bg-slate-800"></label><label class="sm:col-span-2 text-sm font-semibold">Preview text<input name="preview_text" :value="edit?.preview_text||''" class="mt-2 w-full rounded-xl border-slate-300 dark:bg-slate-800"></label>@endif<label class="sm:col-span-2 text-sm font-semibold">Body<textarea name="body" required rows="9" x-text="edit?.body||''" class="mt-2 w-full rounded-xl border-slate-300 dark:bg-slate-800"></textarea></label><label class="text-sm font-semibold">Button text<input name="button_text" :value="edit?.button_text||''" class="mt-2 w-full rounded-xl border-slate-300 dark:bg-slate-800"></label><label class="text-sm font-semibold">Button URL<input name="button_url" :value="edit?.button_url||''" class="mt-2 w-full rounded-xl border-slate-300 dark:bg-slate-800"></label><div class="sm:col-span-2 rounded-xl bg-slate-50 p-4 text-xs text-slate-500 dark:bg-slate-800"><strong>Variables:</strong> @verbatim{{customer_name}}, {{order_number}}, {{order_total}}, {{order_status}}, {{tracking_url}}, {{store_name}}, {{store_phone}}@endverbatim</div><label class="flex gap-2 text-sm"><input type="checkbox" name="is_important" value="1" :checked="edit?.is_important"> Important</label><label class="flex gap-2 text-sm"><input type="checkbox" name="is_active" value="1" :checked="edit?.is_active"> Enabled</label></div><div class="flex justify-end gap-3 border-t p-5"><button type="button" @click="open=false" class="rounded-xl border px-4 py-2.5">Cancel</button><button class="rounded-xl bg-indigo-600 px-5 py-2.5 font-semibold text-white">Save template</button></div></form></div></div>
</div></x-admin-layout>
