<div>
    <!-- Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less. - Maria Skłodowska-Curie -->
</div>
<x-admin-layout :title="ucfirst($channel).' Templates'"><div x-data="{open:@js($errors->any()), edit:null, remove:null}" class="min-h-screen bg-slate-50 dark:bg-[#111827] dark:text-slate-100"><x-admin-sidebar/><main class="min-w-0 lg:pl-72"><x-admin-topbar/><div class="mx-auto max-w-7xl p-5 sm:p-8">
<div class="mb-6 flex items-end justify-between"><div><p class="text-sm font-semibold text-indigo-600">Communication</p><h1 class="text-2xl font-bold">{{ ucfirst($channel) }} body formats</h1><p class="mt-2 text-sm text-slate-500">Create reusable message content for faster sending.</p></div><button @click="edit=null;open=true" class="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">+ Add format</button></div>
@if(session('status'))<div class="mb-5 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">{{session('status')}}</div>@endif @if($errors->any())<div class="mb-5 rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{{$errors->first()}}</div>@endif
<div class="overflow-hidden rounded-2xl border bg-white dark:border-slate-800 dark:bg-[#161f2e]"><table class="w-full min-w-[700px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-slate-800"><tr><th class="px-6 py-4">Name</th>@if($channel==='email')<th class="px-6 py-4">Subject</th>@endif<th class="px-6 py-4">Body</th><th class="px-6 py-4 text-right">Actions</th></tr></thead><tbody class="divide-y">@forelse($templates as $template)<tr><td class="px-6 py-4 font-semibold">{{$template->name}} @if($template->is_important)<span class="ml-1 rounded bg-amber-50 px-2 py-1 text-xs text-amber-700">Important</span>@endif</td>@if($channel==='email')<td class="px-6 py-4">{{$template->subject}}</td>@endif<td class="max-w-md truncate px-6 py-4 text-slate-500">{{strip_tags($template->body)}}</td><td class="px-6 py-4"><div class="flex justify-end gap-2"><button @click='edit=@json($template);open=true' class="rounded-lg bg-indigo-50 px-3 py-2 text-xs font-semibold text-indigo-700">Edit</button><button @click="remove={{$template->id}}" class="rounded-lg bg-rose-50 px-3 py-2 text-xs font-semibold text-rose-700">Delete</button></div></td></tr>@empty<tr><td colspan="4" class="p-14 text-center text-slate-500">No format created yet.</td></tr>@endforelse</tbody></table>@if($templates->hasPages())<div class="border-t p-4">{{$templates->links()}}</div>@endif</div></div></main>
<div x-cloak x-show="open" class="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><div @click.outside="open=false" class="w-full max-w-2xl rounded-2xl bg-white dark:bg-[#161f2e]"><div class="flex justify-between border-b p-5"><h2 class="text-xl font-bold" x-text="edit?'Edit format':'Add format'"></h2><button @click="open=false">✕</button></div><form method="POST" :action="edit?'{{url('/communication/templates/'.$channel)}}/'+edit.id:'{{route('communication.templates.store',$channel)}}'">@csrf<input x-show="edit" type="hidden" name="_method" value="PUT"><div class="space-y-4 p-5"><label class="block text-sm font-semibold">Format name<input name="name" required :value="edit?.name||''" class="mt-2 w-full rounded-xl border-slate-300 dark:bg-slate-800"></label>@if($channel==='email')<label class="block text-sm font-semibold">Subject<input name="subject" required :value="edit?.subject||''" class="mt-2 w-full rounded-xl border-slate-300 dark:bg-slate-800"></label>@endif<label class="block text-sm font-semibold">Message body<textarea name="body" required rows="8" x-text="edit?.body||''" class="mt-2 w-full rounded-xl border-slate-300 dark:bg-slate-800"></textarea></label><label class="flex gap-2 text-sm"><input type="checkbox" name="is_important" value="1" :checked="edit?.is_important"> Mark as important</label></div><div class="flex justify-end gap-3 border-t p-5"><button type="button" @click="open=false" class="rounded-xl border px-4 py-2.5">Cancel</button><button class="rounded-xl bg-indigo-600 px-5 py-2.5 font-semibold text-white">Save format</button></div></form></div></div>
<div x-cloak x-show="remove" class="fixed inset-0 z-[60] grid place-items-center bg-slate-950/50 p-4"><form method="POST" :action="'{{url('/communication/templates/'.$channel)}}/'+remove" class="w-full max-w-sm rounded-2xl bg-white p-6 dark:bg-[#161f2e]">@csrf @method('DELETE')<h3 class="text-lg font-bold">Delete this format?</h3><div class="mt-5 flex justify-end gap-3"><button type="button" @click="remove=null" class="rounded-xl border px-4 py-2">Cancel</button><button class="rounded-xl bg-rose-600 px-4 py-2 text-white">Delete</button></div></form></div>
</div></x-admin-layout>
