@php($editing = $post->exists)
@php($selectedCategoryIds = old('category_ids', $editing ? $post->categories()->pluck('blog_categories.id')->all() : []))
<x-admin-layout title="{{ $editing ? 'Edit Blog' : 'Add New Blog' }}">
    <x-slot:head>
        <script src="https://cdn.ckeditor.com/ckeditor5/41.4.2/classic/ckeditor.js"></script>
        <style>.blog-content-editor .ck-editor__editable{min-height:380px}.dark .blog-content-editor .ck-toolbar{background:#172033;border-color:#334155}.dark .blog-content-editor .ck-editor__editable{background:#1e293b;color:#e2e8f0;border-color:#334155}</style>
    </x-slot:head>
    <div class="ds-page">
        <div x-cloak x-show="menuOpen" @click="menuOpen=false" class="fixed inset-0 z-30 bg-slate-950/50 lg:hidden"></div>
        <x-admin-sidebar />
        <main class="min-w-0 lg:pl-72"><x-admin-topbar />
            <form @if($editing) data-ds-editable data-ds-editable-start="edit" @endif method="POST" action="{{ $editing ? route('blog.update', $post) : route('blog.store') }}" enctype="multipart/form-data">
                @csrf @if($editing) @method('PUT') @endif
                <div class="mx-auto max-w-[1500px] p-5 sm:p-8">
                    <div class="mb-6 flex flex-wrap items-center justify-between gap-4"><div><a href="{{ route('blog.index') }}" class="text-sm font-semibold text-indigo-600">&larr; Blog</a><h1 class="mt-2 text-2xl font-bold">{{ $editing ? 'Edit blog' : 'Add new blog' }}</h1></div>@if($editing)<a href="{{ route('blog.show', $post) }}" class="ds-button-secondary">Preview</a>@endif</div>
                    @if ($errors->any())<div class="mb-6 rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-700">Please fix the highlighted fields.</div>@endif
                    <div class="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_360px]">
                        <div class="space-y-6">
                            <section x-data="{ title: @js(old('title', $post->title)), slug: @js(old('slug', $post->slug)), editingSlug:false, slugify(v){return v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')}}" class="ds-card ds-card-body">
                                <label class="ds-field-label">Blog title <span class="text-rose-500">*</span></label><input name="title" x-model="title" @input="if(!editingSlug) slug=slugify(title)" required class="ds-input ds-control font-medium">@error('title')<p class="ds-error">{{ $message }}</p>@enderror
                                <div data-ds-editable-ignore class="mt-2 flex flex-wrap items-center gap-2 text-xs text-slate-500"><b>Permalink:</b><span class="inline-flex min-w-0 text-indigo-600"><span class="whitespace-nowrap">{{ url('/blog') }}/</span><span x-show="!editingSlug" x-text="slug || 'blog-slug'" class="break-all"></span></span><input x-cloak x-show="editingSlug" x-model="slug" class="rounded border-slate-300 px-2 py-1 text-sm dark:bg-slate-800"><button type="button" @click="editingSlug=!editingSlug" class="rounded border border-indigo-400 px-2 py-1 font-semibold text-indigo-600" x-text="editingSlug?'Done':'Edit'"></button><input type="hidden" name="slug" :value="slug"></div>@error('slug')<p class="ds-error">{{ $message }}</p>@enderror
                            </section>
                            <section class="ds-card ds-card-body blog-content-editor"><h2 class="font-bold">Content</h2><textarea id="blog-content" name="content" data-ds-rich-text class="mt-4">{{ old('content', $post->content) }}</textarea>@error('content')<p class="ds-error">{{ $message }}</p>@enderror</section>
                            <section class="ds-card ds-card-body"><label class="ds-field-label">Excerpt</label><textarea name="excerpt" rows="4" maxlength="1000" class="ds-textarea ds-control" placeholder="Short summary shown in blog listings">{{ old('excerpt', $post->excerpt) }}</textarea>@error('excerpt')<p class="ds-error">{{ $message }}</p>@enderror</section>
                            <section class="ds-card ds-card-body"><h2 class="font-bold">Gallery</h2><p class="ds-help">Up to 12 supporting images. PNG, JPG or WebP; maximum 4 MB each.</p><input name="gallery[]" type="file" multiple accept="image/png,image/jpeg,image/webp" class="ds-file-input mt-4">@if($post->gallery_paths)<div class="mt-4 grid grid-cols-4 gap-3">@foreach($post->gallery_paths as $image)<img src="{{ asset('storage/'.$image) }}" alt="" class="aspect-square rounded-xl object-cover">@endforeach</div>@endif @error('gallery.*')<p class="ds-error">{{ $message }}</p>@enderror</section>
                            <section class="ds-card ds-card-body"><h2 class="font-bold">Search engine optimization</h2><div class="mt-5 grid gap-5"><div><label class="ds-field-label">Focus keyword</label><input id="focus-keyword-input" name="focus_keyword" value="{{ old('focus_keyword', $post->focus_keyword) }}" maxlength="100" class="ds-input ds-control"></div><div><label class="ds-field-label">SEO title</label><input id="blog-seo-title" name="seo_title" value="{{ old('seo_title', $post->seo_title) }}" maxlength="60" class="ds-input ds-control"><p class="ds-help">Recommended maximum: 60 characters.</p></div><div><label class="ds-field-label">Meta description</label><textarea id="blog-meta-description" name="meta_description" maxlength="160" rows="3" class="ds-textarea ds-control">{{ old('meta_description', $post->meta_description) }}</textarea><p class="ds-help">Recommended maximum: 160 characters.</p></div></div></section>
                        </div>
                        <aside class="space-y-6">
                            <section class="ds-card ds-card-body"><h2 class="font-bold">Publish</h2><div class="mt-4 space-y-4"><div><label class="ds-field-label">Status</label><select name="status" class="ds-select ds-control"><option value="draft" @selected(old('status',$post->status ?: 'draft')==='draft')>Draft</option><option value="published" @selected(old('status',$post->status)==='published')>Published</option></select></div><div><label class="ds-field-label">Visibility</label><select name="visibility" class="ds-select ds-control"><option value="public" @selected(old('visibility',$post->visibility ?: 'public')==='public')>Public</option><option value="private" @selected(old('visibility',$post->visibility)==='private')>Private</option></select></div><div><label class="ds-field-label">Publish date</label><input name="published_at" type="datetime-local" value="{{ old('published_at', $post->published_at?->format('Y-m-d\TH:i')) }}" class="ds-input ds-control"></div></div><button class="ds-button-primary mt-5 w-full justify-center">{{ $editing ? 'Save changes' : 'Publish blog' }}</button></section>
                            <section class="ds-card ds-card-body"><h2 class="font-bold">Blog categories</h2><div class="mt-4 max-h-64 space-y-2 overflow-y-auto rounded-xl border border-slate-200 p-3 dark:border-slate-700">@forelse($categories as $category)<x-blog-category-checkbox :category="$category" :selected-ids="$selectedCategoryIds" />@empty<p class="text-sm text-slate-500">No blog categories yet.</p>@endforelse</div><a href="{{ route('blog.categories') }}" class="mt-3 inline-flex text-sm font-semibold text-indigo-600">+ Add new category</a></section>
                            <section class="ds-card ds-card-body"><h2 class="font-bold">Featured image</h2><input name="featured_image" type="file" accept="image/png,image/jpeg,image/webp" class="ds-file-input mt-4">@if($post->featured_image_path)<img src="{{ asset('storage/'.$post->featured_image_path) }}" alt="" class="mt-4 aspect-video w-full rounded-xl object-cover">@endif @error('featured_image')<p class="ds-error">{{ $message }}</p>@enderror</section>
                            <section class="ds-card ds-card-body"><label class="ds-field-label">Tags</label><input name="tags" value="{{ old('tags', implode(', ', $post->tags ?? [])) }}" class="ds-input ds-control" placeholder="news, guide, featured"><p class="ds-help">Separate tags with commas.</p></section>
                        </aside>
                    </div>
                </div>
            </form>
        </main>
    </div>
    <x-slot:scripts><script>ClassicEditor.create(document.querySelector('#blog-content'),{toolbar:{items:['heading','|','bold','italic','link','bulletedList','numberedList','|','blockQuote','insertTable','mediaEmbed','|','undo','redo'],shouldNotGroupWhenFull:true}}).then(editor=>{const field=document.querySelector('#blog-content');field.closest('form')?.dispatchEvent(new CustomEvent('ds-editor-ready',{detail:{editor,control:field,wrapper:editor.ui.view.element}}));}).catch(error=>console.error(error));</script></x-slot:scripts>
</x-admin-layout>
