<x-admin-layout title="Blog">
    <div class="ds-page"><div x-cloak x-show="menuOpen" @click="menuOpen=false" class="fixed inset-0 z-30 bg-slate-950/50 lg:hidden"></div><x-admin-sidebar />
        <main class="min-w-0 lg:pl-72"><x-admin-topbar /><div class="mx-auto max-w-7xl p-5 sm:p-8">
            <div class="mb-6 flex items-end justify-between gap-4"><div><p class="text-sm font-semibold text-indigo-600">Content</p><h1 class="mt-1 text-2xl font-bold">Blog posts</h1><p class="mt-2 text-sm text-slate-500">Manage website articles, drafts and publishing.</p></div><a href="{{ route('blog.create') }}" class="ds-button-primary inline-flex items-center gap-2">+ Add new blog</a></div>
            @if(session('status'))<div class="mb-6 rounded-xl bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-700">{{ session('status') }}</div>@endif
            <section class="ds-card overflow-hidden"><div class="overflow-x-auto"><table class="w-full min-w-[900px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wider text-slate-500 dark:bg-slate-800/60"><tr><th class="px-5 py-4">Post</th><th class="px-5 py-4">Category</th><th class="px-5 py-4">Author</th><th class="px-5 py-4">Status</th><th class="px-5 py-4">Published</th><th class="px-5 py-4 text-right">Actions</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">
                @forelse($posts as $post)<tr class="hover:bg-slate-50/70 dark:hover:bg-slate-800/30"><td class="px-5 py-4"><div class="flex items-center gap-3">@if($post->featured_image_path)<img src="{{ asset('storage/'.$post->featured_image_path) }}" alt="" class="h-12 w-16 rounded-xl object-cover">@else<div class="grid h-12 w-16 place-items-center rounded-xl bg-slate-100 text-slate-400 dark:bg-slate-800">Image</div>@endif<div><p class="font-semibold">{{ $post->title }}</p><p class="text-xs text-slate-400">/{{ $post->slug }}</p></div></div></td><td class="px-5 py-4 text-slate-500">{{ $post->categories->pluck('name')->join(', ') ?: '—' }}</td><td class="px-5 py-4 text-slate-500">{{ $post->author?->name ?: '—' }}</td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $post->status === 'published' ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700' }}">{{ ucfirst($post->status) }}</span></td><td class="px-5 py-4 text-slate-500">{{ $post->published_at?->format('d M Y') ?: 'Not published' }}</td><td class="px-5 py-4"><div class="flex justify-end gap-2"><a href="{{ route('blog.show',$post) }}" class="grid h-8 w-8 place-items-center rounded-full bg-slate-200 hover:bg-blue-500 hover:text-white" title="View">����</a><a href="{{ route('blog.edit',$post) }}" class="grid h-8 w-8 place-items-center rounded-full bg-slate-200" title="Edit">✎</a><form method="POST" action="{{ route('blog.destroy',$post) }}" onsubmit="return confirm('Delete this blog post?')">@csrf @method('DELETE')<button class="grid h-8 w-8 place-items-center rounded-full bg-slate-200 hover:bg-rose-500 hover:text-white" title="Delete">×</button></form></div></td></tr>
                @empty<tr><td colspan="6" class="px-6 py-14 text-center"><p class="font-semibold">No blog posts found</p><a href="{{ route('blog.create') }}" class="mt-4 inline-flex text-sm font-semibold text-indigo-600">Add your first blog post</a></td></tr>@endforelse
            </tbody></table></div>@if($posts->hasPages())<div class="border-t px-5 py-4 dark:border-slate-800">{{ $posts->links() }}</div>@endif</section>
        </div></main>
    </div>
</x-admin-layout>
