<x-admin-layout title="Product Preview">
    <div class="min-h-screen bg-slate-50 text-slate-900 dark:bg-[#111827] dark:text-slate-100">
        <div x-cloak x-show="menuOpen" @click="menuOpen = false" class="fixed inset-0 z-30 bg-slate-950/50 lg:hidden"></div>
        <x-admin-sidebar />
        <main class="min-w-0 lg:pl-72"><x-admin-topbar />
            <div class="mx-auto max-w-6xl p-5 sm:p-8">
                <div class="mb-6 flex flex-wrap items-center justify-between gap-4"><div><a href="{{ route('products.index') }}" class="text-sm font-semibold text-indigo-600">&larr; Products</a><h1 class="mt-2 text-2xl font-bold">Product preview</h1></div><a href="{{ route('products.edit', $product) }}" class="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">Edit product</a></div>
                <article class="overflow-hidden rounded-2xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-[#161f2e]">
                    <div class="grid gap-8 p-6 md:grid-cols-2 md:p-8">
                        <div>@if ($product->featured_image_path)<img src="{{ asset('storage/'.$product->featured_image_path) }}" alt="{{ $product->title }}" class="aspect-square w-full rounded-2xl object-cover">@else<div class="grid aspect-square place-items-center rounded-2xl bg-slate-100 text-slate-400 dark:bg-slate-800">No product image</div>@endif @if ($product->gallery_paths)<div class="mt-4 grid grid-cols-4 gap-3">@foreach ($product->gallery_paths as $image)<img src="{{ asset('storage/'.$image) }}" alt="" class="aspect-square rounded-xl object-cover">@endforeach</div>@endif</div>
                        <div><div class="flex flex-wrap gap-2"><span class="rounded-full bg-indigo-50 px-3 py-1 text-xs font-semibold text-indigo-700 dark:bg-indigo-500/15 dark:text-indigo-300">{{ ucfirst($product->status) }}</span>@foreach ($product->tags ?? [] as $tag)<span class="rounded-full bg-slate-100 px-3 py-1 text-xs dark:bg-slate-800">{{ $tag }}</span>@endforeach</div><h2 class="mt-4 text-3xl font-bold tracking-tight">{{ $product->title }}</h2><p class="mt-3 text-sm text-slate-500">{{ $product->brand?->name }} @if($product->category) &middot; {{ $product->category->name }} @endif @if($product->unit) &middot; {{ $product->unit->name }} @endif</p><div class="mt-6 flex items-baseline gap-3">@if($product->sale_price)<span class="text-3xl font-bold">{{ number_format((float) $product->sale_price, 2) }}</span><span class="text-lg text-slate-400 line-through">{{ number_format((float) $product->price, 2) }}</span>@elseif($product->price)<span class="text-3xl font-bold">{{ number_format((float) $product->price, 2) }}</span>@endif</div>@if ($product->short_description)<p class="mt-6 leading-7 text-slate-600 dark:text-slate-300">{{ $product->short_description }}</p>@endif<dl class="mt-6 grid grid-cols-2 gap-4 rounded-xl bg-slate-50 p-4 text-sm dark:bg-slate-800/60"><div><dt class="text-slate-500">SKU</dt><dd class="mt-1 font-semibold">{{ $product->sku ?: '—' }}</dd></div><div><dt class="text-slate-500">Stock</dt><dd class="mt-1 font-semibold">{{ $product->stock_quantity }}</dd></div><div><dt class="text-slate-500">Visibility</dt><dd class="mt-1 font-semibold">{{ ucfirst($product->visibility) }}</dd></div><div><dt class="text-slate-500">Published</dt><dd class="mt-1 font-semibold">{{ $product->published_at?->format('d M Y, h:i A') ?: 'Not published' }}</dd></div></dl></div>
                    </div>
                    @if ($product->description)<div class="border-t border-slate-200 p-6 dark:border-slate-800 md:p-8"><h3 class="text-lg font-bold">Description</h3><div class="prose mt-4 max-w-none leading-7 text-slate-600 dark:prose-invert dark:text-slate-300">{!! $product->description !!}</div></div>@endif
                    @if ($product->video_path)<div class="border-t border-slate-200 p-6 dark:border-slate-800 md:p-8"><h3 class="mb-4 text-lg font-bold">Product video</h3><video src="{{ asset('storage/'.$product->video_path) }}" controls class="max-h-[520px] w-full rounded-2xl bg-black"></video></div>@endif
                </article>
            </div>
        </main>
    </div>
</x-admin-layout>
