@php($isBrand = $type === 'brand')
@php($label = $isBrand ? 'Brand' : 'Unit')
@php($plural = $isBrand ? 'Brands' : 'Units')
@php($indexRoute = $isBrand ? 'brands.index' : 'units.index')
@php($storeRoute = $isBrand ? 'brands.store' : 'units.store')
@php($updateUrl = $isBrand ? url('/brands') : url('/units'))
@php($destroyRoute = $isBrand ? 'brands.destroy' : 'units.destroy')

<x-admin-layout title="{{ $plural }} - Shopwise">
    <div class="min-h-screen bg-slate-50 text-slate-900 dark:bg-[#111827] dark:text-slate-100 {{ $isBrand ? '' : 'units-taxonomy' }}" x-data="{ modalOpen: false, editingId: null, editingName: '', editingSlug: '', editingDescription: '', editingExtraDescription: '' }">
        <div x-cloak x-show="menuOpen" @click="menuOpen = false" class="fixed inset-0 z-30 bg-slate-950/50 lg:hidden"></div>
        <x-admin-sidebar />
        <main class="min-w-0 lg:pl-72">
            <x-admin-topbar />
            <div class="mx-auto max-w-7xl p-5 sm:p-8">
                <div class="mb-5 flex items-center justify-between gap-4"><div><p class="text-sm font-medium text-indigo-600 dark:text-indigo-400">Products</p><h1 class="text-2xl font-bold">{{ $plural }}</h1></div><button @click="editingId = null; editingName = ''; editingSlug = ''; editingDescription = ''; editingExtraDescription = ''; modalOpen = true" class="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-width="2" d="M12 5v14M5 12h14"/></svg>Add new {{ strtolower($label) }}</button></div>
                @if (session('status'))<div class="mb-6 rounded-xl bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-700 dark:bg-emerald-500/15 dark:text-emerald-300">{{ session('status') }}</div>@endif
                <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-[#161f2e]">
                    <div class="flex flex-col gap-4 border-b border-slate-200 p-5 dark:border-slate-800 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="font-bold">{{ $label }} list</h2><p class="mt-1 text-sm text-slate-500">Manage and organize product {{ strtolower($plural) }}.</p></div><form class="flex gap-2"><input class="w-48 rounded-lg border-slate-300 px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-800" placeholder="Search" type="search"><button class="rounded-lg border border-indigo-600 px-3 py-2 text-sm text-indigo-600 hover:bg-indigo-600 hover:text-white">Search</button></form></div>
                    <div class="flex items-center justify-between border-b border-slate-100 bg-slate-50 p-4 dark:border-slate-800 dark:bg-slate-800/50"><div class="flex gap-2"><select class="rounded-md border-slate-300 bg-white py-2 text-sm dark:border-slate-700 dark:bg-slate-800"><option>Bulk actions</option><option>Delete</option></select><button class="rounded-md border border-indigo-600 px-3 py-2 text-sm text-indigo-600">Apply</button></div><span class="text-sm text-slate-500">{{ $items->count() }} items</span></div>
                    <div class="overflow-x-auto"><table class="w-full min-w-[650px] text-left text-sm"><thead class="border-b border-slate-200 bg-slate-50 text-slate-500 dark:border-slate-700 dark:bg-slate-800/60"><tr><th class="px-4 py-3"><input type="checkbox" class="rounded border-slate-300 text-indigo-600"></th><th class="px-4 py-3">Name</th><th class="px-4 py-3">Slug</th><th class="px-4 py-3 text-right">Actions</th></tr></thead><tbody>@forelse ($items as $item)<tr class="border-b border-slate-100 dark:border-slate-800"><td class="px-4 py-4"><input type="checkbox" class="rounded border-slate-300 text-indigo-600"></td><td class="px-4 py-4 font-medium text-indigo-600 dark:text-indigo-400">{{ $item->name }}</td><td class="px-4 py-4 text-slate-500">{{ $item->slug ?? str($item->name)->slug() }}</td><td class="px-4 py-4"><div class="flex justify-end gap-2"><button @click="editingId = {{ $item->id }}; editingName = @js($item->name); editingSlug = @js($item->slug); @if($isBrand) editingDescription = @js($item->description); editingExtraDescription = @js($item->extra_description); @endif modalOpen = true" title="Edit {{ strtolower($label) }}" class="grid h-8 w-8 place-items-center rounded-full bg-slate-200 text-slate-700 hover:bg-slate-300 dark:bg-slate-700 dark:text-slate-200"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-width="2" d="m4 20 4.2-1 9.6-9.6a2.1 2.1 0 0 0-3-3L5.2 16 4 20Z"/></svg></button><form method="POST" action="{{ route($destroyRoute, $item) }}" onsubmit="return confirm('Delete this {{ strtolower($label) }}?');">@csrf @method('DELETE')<button title="Delete {{ strtolower($label) }}" class="grid h-8 w-8 place-items-center rounded-full bg-slate-200 text-slate-700 hover:bg-rose-500 hover:text-white dark:bg-slate-700 dark:text-slate-200"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-width="2" d="M6 7h12m-8 4v5m4-5v5M9 7l1-3h4l1 3m-8 0 1 13h8l1-13"/></svg></button></form></div></td></tr>@empty<tr><td colspan="4" class="p-10 text-center text-slate-500">No {{ strtolower($plural) }} yet. <button @click="modalOpen = true" class="font-semibold text-indigo-600">Add new {{ strtolower($label) }}</button></td></tr>@endforelse</tbody></table></div>
                </section>
            </div>
        </main>
        <div x-cloak x-show="modalOpen" @keydown.escape.window="modalOpen = false" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div @click.outside="modalOpen = false" class="w-full max-w-lg overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl dark:border-slate-700 dark:bg-[#161f2e]"><div class="flex items-center justify-between border-b px-5 py-4" :class="editingId ? 'border-amber-100 bg-amber-50 dark:border-amber-500/20 dark:bg-amber-500/10' : 'border-indigo-100 bg-indigo-50 dark:border-indigo-500/20 dark:bg-indigo-500/10'"><h2 class="text-xl font-bold" x-text="editingId ? 'Edit {{ $label }}' : 'Add new {{ $label }}'"></h2><x-modal-close-button @click="modalOpen = false" /></div><form data-ds-dirty-submit method="POST" :action="editingId ? '{{ $updateUrl }}/' + editingId : '{{ route($storeRoute) }}'" class="p-5 sm:p-7">@csrf<input x-show="editingId" :disabled="!editingId" type="hidden" name="_method" value="PUT"><label class="text-sm font-semibold">Name <span class="text-rose-500">*</span></label><input x-model="editingName" name="name" required class="mt-2 w-full rounded-xl border-slate-200 px-3 py-2.5 text-sm dark:border-slate-700 dark:bg-slate-800" :placeholder="'e.g. ' + (editingId ? '' : '{{ $isBrand ? 'Apple' : 'Piece' }}')">@if ($isBrand)<div class="mt-5"><label for="brand-slug" class="ds-field-label">Slug</label><input id="brand-slug" x-model="editingSlug" name="slug" maxlength="100" class="ds-input ds-control" placeholder="Leave empty to generate automatically"><p class="ds-help">Used in the storefront URL. Leave empty to generate it from the name.</p>@error('slug')<p class="ds-error">{{ $message }}</p>@enderror</div>@endif @if ($isBrand)<div class="mt-5"><label for="brand-description" class="ds-field-label">Top description</label><textarea id="brand-description" x-model="editingDescription" name="description" rows="4" class="ds-textarea ds-control"></textarea><p class="ds-help">Shown below the brand breadcrumb and title.</p></div><div class="mt-5"><label for="brand-extra-description" class="ds-field-label">Bottom description</label><textarea id="brand-extra-description" x-model="editingExtraDescription" name="extra_description" rows="5" class="ds-textarea ds-control"></textarea><p class="ds-help">Shown after the product list and pagination.</p></div>@endif<div class="mt-6 flex justify-end gap-3"><button type="button" @click="modalOpen = false" class="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold dark:border-slate-700">Cancel</button><button class="rounded-xl bg-indigo-600 px-5 py-2.5 text-sm font-semibold text-white" x-text="editingId ? 'Save changes' : 'Save {{ $label }}'"></button></div></form></div></div>
    </div>
</x-admin-layout>
