<x-admin-layout title="Edit {{ $order->order_number }}">
    <div class="min-h-screen bg-slate-50 text-slate-900 dark:bg-[#111827] dark:text-slate-100">
        <div x-cloak x-show="menuOpen" @click="menuOpen = false" class="fixed inset-0 z-30 bg-slate-950/50 lg:hidden"></div><x-admin-sidebar />
        <main class="min-w-0 lg:pl-72"><x-admin-topbar /><div class="mx-auto max-w-3xl p-5 sm:p-8">
            <a href="{{ route('orders.show', $order) }}" class="text-sm font-semibold text-indigo-600 dark:text-indigo-400">← Back to order</a>
            <section class="ds-card mt-5 overflow-hidden shadow-sm"><div class="border-b border-indigo-100 bg-indigo-50 px-5 py-5 dark:border-indigo-500/20 dark:bg-indigo-500/10 sm:px-7"><p class="text-xs font-semibold uppercase tracking-wider text-indigo-600 dark:text-indigo-400">{{ $order->order_number }}</p><h1 class="mt-1 text-2xl font-bold">Edit order</h1><p class="mt-1 text-sm text-slate-500">Update customer and delivery information. Use the order page for status changes.</p></div>
                <form data-ds-editable data-ds-editable-start="edit" method="POST" action="{{ route('orders.update', $order) }}" x-data="{ items: @js($order->items->map(fn ($item) => ['quantity' => (int) $item->quantity, 'price' => (float) $item->unit_price])->values()), shipping: {{ (float) $order->shipping_cost }}, total() { return this.items.reduce((sum, item) => sum + (Number(item.quantity) || 0) * item.price, this.shipping) } }">@csrf @method('PUT')
                    <div class="grid gap-5 p-5 sm:grid-cols-2 sm:p-7"><div><label for="customer_name" class="ds-field-label">Customer name</label><input id="customer_name" name="customer_name" value="{{ old('customer_name', $order->customer_name) }}" class="ds-input ds-control" required>@error('customer_name')<p class="ds-error">{{ $message }}</p>@enderror</div><div><label for="customer_phone" class="ds-field-label">Phone</label><input id="customer_phone" name="customer_phone" value="{{ old('customer_phone', $order->customer_phone) }}" class="ds-input ds-control" required>@error('customer_phone')<p class="ds-error">{{ $message }}</p>@enderror</div><div><label for="customer_email" class="ds-field-label">Email</label><input id="customer_email" type="email" name="customer_email" value="{{ old('customer_email', $order->customer_email) }}" class="ds-input ds-control">@error('customer_email')<p class="ds-error">{{ $message }}</p>@enderror</div><div class="sm:col-span-2"><label for="shipping_address" class="ds-field-label">Delivery address</label><textarea id="shipping_address" name="shipping_address" rows="4" class="ds-textarea ds-control" required>{{ old('shipping_address', $order->shipping_address) }}</textarea>@error('shipping_address')<p class="ds-error">{{ $message }}</p>@enderror</div><div class="sm:col-span-2"><label for="customer_note" class="ds-field-label">Customer note</label><textarea id="customer_note" name="customer_note" rows="3" class="ds-textarea ds-control">{{ old('customer_note', $order->customer_note) }}</textarea>@error('customer_note')<p class="ds-error">{{ $message }}</p>@enderror</div>
                    <div class="sm:col-span-2"><div class="mb-3 flex items-end justify-between gap-4"><div><h2 class="font-bold">Order items</h2><p class="mt-1 text-sm text-slate-500">Use − or + to change quantity.</p></div><div class="text-right"><p class="text-xs text-slate-400">New total</p><p class="font-bold text-indigo-700 dark:text-indigo-300">৳<span x-text="total().toFixed(2)"></span></p></div></div><div class="divide-y divide-slate-100 overflow-hidden rounded-xl border border-slate-200 dark:divide-slate-700 dark:border-slate-700">@foreach($order->items as $index=>$item)<div class="p-4"><div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p class="font-semibold">{{ $item->product_title }}</p><p class="mt-1 text-xs text-slate-500">৳{{ number_format((float)$item->unit_price,2) }} each@if($item->product) · {{ $item->product->stock_quantity }} more in stock@endif</p></div><div class="flex items-center justify-between gap-4"><input type="hidden" name="items[{{ $index }}][id]" value="{{ $item->id }}"><div class="flex items-center overflow-hidden rounded-xl border border-slate-200 dark:border-slate-700"><button type="button" @click="items[{{ $index }}].quantity=Math.max(1,Number(items[{{ $index }}].quantity)-1)" class="h-10 w-10 text-lg font-bold hover:bg-slate-100 dark:hover:bg-slate-800" aria-label="Decrease quantity">−</button><input type="number" min="1" max="9999" name="items[{{ $index }}][quantity]" x-model.number="items[{{ $index }}].quantity" class="h-10 w-16 border-y-0 border-slate-200 p-0 text-center font-bold focus:ring-0 dark:border-slate-700 dark:bg-slate-900" required><button type="button" @click="items[{{ $index }}].quantity=Number(items[{{ $index }}].quantity)+1" class="h-10 w-10 text-lg font-bold hover:bg-slate-100 dark:hover:bg-slate-800" aria-label="Increase quantity">+</button></div><p class="w-24 text-right font-bold">৳<span x-text="((Number(items[{{ $index }}].quantity)||0)*{{ (float)$item->unit_price }}).toFixed(2)"></span></p></div></div>@error('items.'.$index.'.quantity')<p class="ds-error">{{ $message }}</p>@enderror</div>@endforeach</div>@error('items')<p class="ds-error">{{ $message }}</p>@enderror</div></div>
                    <div class="flex justify-end gap-3 border-t border-slate-200 bg-slate-50/70 px-5 py-4 dark:border-slate-700 dark:bg-slate-900/20 sm:px-7"><a href="{{ route('orders.show', $order) }}" class="ds-button-secondary inline-flex items-center px-4">Cancel</a><button class="ds-button-primary px-5">Save changes</button></div>
                </form>
            </section>
        </div></main>
    </div>
</x-admin-layout>
