<x-admin-layout title="Orders">
    <div class="min-h-screen bg-slate-50 text-slate-900 dark:bg-[#111827] dark:text-slate-100">
        <div x-cloak x-show="menuOpen" @click="menuOpen = false" class="fixed inset-0 z-30 bg-slate-950/50 lg:hidden"></div>
        <x-admin-sidebar />
        <main class="min-w-0 lg:pl-72">
            <x-admin-topbar />
            <div class="mx-auto max-w-[1600px] p-5 sm:p-8">
                <section x-data="{ view: localStorage.getItem('orders-view') || 'list', knownUnreadCount: {{ $unreadOrderCount }}, newOrdersAvailable: false, setView(value) { this.view = value; localStorage.setItem('orders-view', value) } }" @order-notifications-updated.window="if ($event.detail.unreadCount > knownUnreadCount) { newOrdersAvailable = true } else if ($event.detail.unreadCount < knownUnreadCount) { knownUnreadCount = $event.detail.unreadCount }" class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-[#161f2e]">
                    <div class="p-4 sm:p-5">
                    <div class="flex items-start justify-between gap-4"><div><h1 class="text-lg font-semibold">Orders Management</h1><p class="mt-1 text-xs text-slate-500 dark:text-slate-400">Manage and track all orders</p></div><a href="{{ route('orders.create') }}" class="inline-flex h-10 items-center gap-2 rounded-xl bg-gradient-to-r from-sky-500 to-teal-400 px-4 text-sm font-semibold text-white shadow-sm transition hover:from-sky-600 hover:to-teal-500"><span class="text-lg leading-none">+</span> New Order</a></div>
                    @php
                        $statusCards = [
                            'pending' => ['Pending', $statusCounts->get('pending', 0), 'text-amber-700 bg-amber-50 border-amber-200 dark:text-amber-300 dark:bg-amber-500/10 dark:border-amber-500/20'],
                            'confirmed' => ['Confirmed', $statusCounts->get('confirmed', 0), 'text-cyan-700 bg-cyan-50 border-cyan-200 dark:text-cyan-300 dark:bg-cyan-500/10 dark:border-cyan-500/20'],
                            'processing' => ['Processing', $statusCounts->get('processing', 0), 'text-sky-700 bg-sky-50 border-sky-200 dark:text-sky-300 dark:bg-sky-500/10 dark:border-sky-500/20'],
                            'ready_to_ship' => ['Ready to Ship', $statusCounts->get('ready_to_ship', 0), 'text-indigo-700 bg-indigo-50 border-indigo-200 dark:text-indigo-300 dark:bg-indigo-500/10 dark:border-indigo-500/20'],
                            'shipped' => ['Shipped', $statusCounts->get('shipped', 0), 'text-blue-700 bg-blue-50 border-blue-200 dark:text-blue-300 dark:bg-blue-500/10 dark:border-blue-500/20'],
                            'completed' => ['Completed', $statusCounts->get('completed', 0), 'text-emerald-700 bg-emerald-50 border-emerald-200 dark:text-emerald-300 dark:bg-emerald-500/10 dark:border-emerald-500/20'],
                            'cancelled' => ['Cancelled', $statusCounts->get('cancelled', 0), 'text-rose-700 bg-rose-50 border-rose-200 dark:text-rose-300 dark:bg-rose-500/10 dark:border-rose-500/20'],
                            'returned' => ['Returned', $statusCounts->get('returned', 0), 'text-orange-700 bg-orange-50 border-orange-200 dark:text-orange-300 dark:bg-orange-500/10 dark:border-orange-500/20'],
                        ];
                    @endphp
                    <div class="mt-5 flex gap-3 overflow-x-auto pb-1">
                        @foreach ($statusCards as $status => [$label, $count, $classes])
                            <a href="{{ route('orders.index', array_filter(['search' => request('search'), 'date' => request('date'), 'delivery_area' => request('delivery_area'), 'status' => $status])) }}" class="flex min-w-[125px] flex-1 cursor-pointer transform-none items-center justify-between gap-3 rounded-xl border px-3.5 py-3 transition duration-150 hover:transform-none hover:brightness-95 hover:shadow-none dark:hover:brightness-125 focus:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-sky-400 {{ $classes }}"><span class="text-xs font-semibold">{{ $label }}</span><strong class="text-xl leading-none">{{ $count }}</strong></a>
                        @endforeach
                    </div>
                    <form method="GET" action="{{ route('orders.index') }}" class="mt-5 grid gap-3 lg:grid-cols-[minmax(240px,1fr)_auto_auto_auto_auto_auto_auto]">
                        <label class="relative block"><span class="sr-only">Search orders</span><svg class="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><circle cx="11" cy="11" r="7" stroke-width="1.8"/><path stroke-linecap="round" stroke-width="1.8" d="m20 20-4-4"/></svg><input name="search" value="{{ request('search') }}" placeholder="Search by order ID or customer..." class="h-11 w-full rounded-xl border-slate-200 bg-slate-50 pl-10 pr-4 text-sm focus:border-sky-400 focus:ring-sky-400 dark:border-slate-700 dark:bg-slate-800"></label>
                        <div x-data="{ date: @js(request('date', '')) }" class="relative min-w-[170px]"><label><span class="sr-only">Filter by date</span><span x-cloak x-show="!date" class="pointer-events-none absolute inset-y-0 left-3 flex items-center text-sm text-slate-500">Select date</span><svg x-cloak x-show="!date" class="pointer-events-none absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-sky-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="16" rx="3" stroke-width="1.8"/><path stroke-linecap="round" stroke-width="1.8" d="M8 3v4m8-4v4M3 10h18"/></svg><input x-model="date" type="date" name="date" :class="date ? 'text-slate-600 dark:text-slate-300' : 'text-transparent'" class="h-11 w-full cursor-pointer rounded-xl border-slate-200 bg-slate-50 pl-3 pr-10 text-sm font-medium shadow-sm focus:border-sky-400 focus:bg-white focus:ring-sky-400 dark:border-slate-700 dark:bg-slate-800 dark:focus:bg-slate-900 [&::-webkit-calendar-picker-indicator]:absolute [&::-webkit-calendar-picker-indicator]:inset-0 [&::-webkit-calendar-picker-indicator]:h-full [&::-webkit-calendar-picker-indicator]:w-full [&::-webkit-calendar-picker-indicator]:cursor-pointer [&::-webkit-calendar-picker-indicator]:opacity-0"></label><button x-cloak x-show="date" type="button" @click.stop="date = ''" class="absolute right-2 top-1/2 z-10 grid h-7 w-7 -translate-y-1/2 place-items-center rounded-lg text-slate-400 transition hover:bg-slate-200 hover:text-slate-700 dark:hover:bg-slate-700 dark:hover:text-slate-200" title="Clear date" aria-label="Clear date"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-width="2" d="m7 7 10 10M17 7 7 17"/></svg></button></div>
                        <select name="status" class="h-11 rounded-xl border-slate-200 bg-white pl-4 pr-9 text-sm dark:border-slate-700 dark:bg-slate-800"><option value="">All Status</option>@foreach (['pending', 'confirmed', 'processing', 'ready_to_ship', 'shipped', 'completed', 'cancelled', 'returned'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ App\OrderStatus::from($status)->label() }}</option>@endforeach</select>
                        <select name="delivery_area" class="h-11 rounded-xl border-slate-200 bg-white pl-4 pr-9 text-sm dark:border-slate-700 dark:bg-slate-800"><option value="">All Delivery Areas</option><option value="dhaka_city" @selected(request('delivery_area') === 'dhaka_city')>Dhaka City</option><option value="dhaka_outside" @selected(request('delivery_area') === 'dhaka_outside')>Outside Dhaka City</option><option value="outside_dhaka" @selected(request('delivery_area') === 'outside_dhaka')>Outside Dhaka District</option></select>
                        <button type="submit" title="Apply filters" class="grid h-11 w-11 place-items-center rounded-xl border border-slate-200 bg-white text-slate-500 transition hover:border-sky-400 hover:text-sky-600 dark:border-slate-700 dark:bg-slate-800"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="M4 5h16l-6 7v5l-4 2v-7L4 5Z"/></svg></button>
                        <a href="{{ route('orders.export', request()->only(['search', 'date', 'status', 'delivery_area'])) }}" title="Download CSV" class="grid h-11 w-11 place-items-center rounded-xl border border-slate-200 bg-white text-slate-500 transition hover:border-teal-400 hover:text-teal-600 dark:border-slate-700 dark:bg-slate-800"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="M12 3v12m0 0 4-4m-4 4-4-4M5 19h14"/></svg></a>
                        <div class="flex h-11 rounded-xl border border-slate-200 bg-slate-50 p-1 dark:border-slate-700 dark:bg-slate-800"><button type="button" @click="setView('list')" :class="view === 'list' ? 'bg-white text-sky-600 shadow-sm dark:bg-slate-700' : 'text-slate-400'" class="grid w-9 place-items-center rounded-lg transition" title="List view"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-width="2" d="M9 6h11M9 12h11M9 18h11M4 6h.01M4 12h.01M4 18h.01"/></svg></button><button type="button" @click="setView('grid')" :class="view === 'grid' ? 'bg-white text-sky-600 shadow-sm dark:bg-slate-700' : 'text-slate-400'" class="grid w-9 place-items-center rounded-lg transition" title="Grid view"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-width="2" d="M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z"/></svg></button></div>
                    </form>
                    <div x-cloak x-show="newOrdersAvailable" x-transition class="mt-4 flex items-center justify-between gap-4 rounded-xl border border-indigo-200 bg-indigo-50 px-4 py-3 text-sm text-indigo-800 dark:border-indigo-500/30 dark:bg-indigo-500/10 dark:text-indigo-300"><span><strong>New orders available.</strong> Refresh when you are ready.</span><button type="button" @click="window.location.reload()" class="shrink-0 rounded-lg bg-indigo-600 px-3 py-2 text-xs font-semibold text-white hover:bg-indigo-700">Refresh list</button></div>
                    </div>
                    @if (session('status'))<div class="mx-5 mb-5 rounded-xl bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-700 dark:bg-emerald-500/15 dark:text-emerald-300">{{ session('status') }}</div>@endif
                    <div class="border-t border-slate-200 dark:border-slate-800">
                    <div x-show="view === 'list'" class="overflow-x-auto">
                        <table class="w-full min-w-[1120px] text-left text-sm">
                            <thead class="bg-slate-50 text-xs uppercase tracking-wider text-slate-500 dark:bg-slate-800/60 dark:text-slate-400"><tr><th class="w-[110px] px-4 py-4">Order</th><th class="px-6 py-4">Customer</th><th class="w-[180px] px-4 py-4">Products</th><th class="px-6 py-4">Delivery</th><th class="w-[180px] px-4 py-4">অর্ডার নোট</th><th class="px-6 py-4">Amount</th><th class="px-6 py-4">Status</th><th class="px-6 py-4">Date</th><th class="px-6 py-4 text-right">Actions</th></tr></thead>
                            <tbody class="divide-y divide-slate-100 dark:divide-slate-800">
                                @forelse ($orders as $order)
                                    <tr class="align-top transition {{ $order->viewed_at ? 'hover:bg-slate-50/70 dark:hover:bg-slate-800/30' : 'bg-indigo-50/70 hover:bg-indigo-50 dark:bg-indigo-500/10 dark:hover:bg-indigo-500/15' }}">
                                        <td class="w-[110px] whitespace-nowrap px-4 py-4 text-xs font-semibold"><a href="{{ route('orders.show', $order) }}" class="inline-flex items-center gap-1.5 text-indigo-600 transition hover:text-indigo-800 hover:underline dark:text-indigo-400 dark:hover:text-indigo-300">@if ($order->viewed_at === null)<span class="h-2 w-2 rounded-full bg-rose-500"></span>@endif{{ $order->order_number }}</a></td>
                                        <td class="px-6 py-4"><p class="font-medium">{{ $order->customer_name }}</p><p class="mt-1.5 flex items-center gap-1.5 whitespace-nowrap text-xs text-slate-500"><svg class="h-3.5 w-3.5 shrink-0 text-sky-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="M6.6 3h3l1.5 4-2 1.7a15 15 0 0 0 6.2 6.2l1.7-2 4 1.5v3A2.6 2.6 0 0 1 18.4 20C10.4 20 4 13.6 4 5.6A2.6 2.6 0 0 1 6.6 3Z"/></svg>{{ $order->customer_phone }}@if ($order->customer_order_count > 1)<a href="{{ route('orders.index', ['search' => $order->customer_phone]) }}" title="{{ $order->customer_order_count }} orders from this customer" class="ml-1 inline-flex rounded-full bg-violet-50 px-2 py-0.5 text-[10px] font-semibold text-violet-700 transition hover:bg-violet-100 dark:bg-violet-500/15 dark:text-violet-300">Repeat</a>@endif</p>@if ($order->customer_email)<p class="mt-1.5 flex items-center gap-1.5 text-xs text-slate-400"><svg class="h-3.5 w-3.5 shrink-0 text-indigo-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="14" rx="2" stroke-width="1.8"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="m4 7 8 6 8-6"/></svg>{{ $order->customer_email }}</p>@endif</td>
                                        <td class="w-[180px] px-4 py-4"><div class="max-w-[170px] space-y-1.5">@foreach ($order->items as $item)<p class="break-words">@if ($item->product)<a href="{{ route('catalog.show', $item->product->slug) }}" class="transition hover:text-indigo-600 dark:hover:text-indigo-400">{{ $item->product_title }}</a>@else{{ $item->product_title }}@endif</p>@endforeach</div></td>
                                        <td class="max-w-64 px-6 py-4">@php $deliveryArea = (App\Services\DeliveryCharges::AREAS[$order->delivery_area] ?? match ((int) $order->shipping_cost) { 50 => 'Dhaka City', 80 => 'Outside Dhaka City', 100 => 'Outside Dhaka District', default => 'Delivery' }); @endphp<p class="text-xs leading-5 text-slate-500 dark:text-slate-400">{{ $order->shipping_address }}</p></td>
                                        <td class="w-[180px] px-4 py-4 text-sm leading-5 text-slate-500 dark:text-slate-400">{{ $order->customer_note ?: '—' }}</td>
                                        <td class="whitespace-nowrap px-6 py-4"><div class="space-y-1.5 text-xs"><div class="flex justify-between gap-4 text-slate-500"><span>Products</span><span>৳{{ number_format((float) $order->subtotal, 2) }}</span></div><div class="flex items-center justify-between gap-4 text-slate-500"><span class="flex items-center gap-1.5 rounded-lg bg-sky-50 px-2 py-1 font-semibold text-sky-700 ring-1 ring-inset ring-sky-100 dark:bg-sky-500/10 dark:text-sky-300 dark:ring-sky-500/20"><svg class="h-3.5 w-3.5 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="M3 7h11v10H3V7Zm11 3h3l4 4v3h-7v-7Zm-7 9a2 2 0 1 0 0-4 2 2 0 0 0 0 4Zm10 0a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z"/></svg>{{ $deliveryArea }}</span><span>৳{{ number_format((float) $order->shipping_cost, 2) }}</span></div><div class="flex justify-between gap-4 border-t border-slate-200 pt-1.5 font-bold text-slate-900 dark:border-slate-700 dark:text-slate-100"><span>Total</span><span>৳{{ number_format((float) $order->total, 2) }}</span></div></div></td>
                                        <td class="px-6 py-4"><span class="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-semibold capitalize text-amber-700 dark:bg-amber-500/15 dark:text-amber-300">{{ str_replace('_', ' ', $order->status) }}</span></td>
                                        <td class="whitespace-nowrap px-6 py-4 text-slate-500 dark:text-slate-400">{{ $order->created_at->format('M d, Y') }}<p class="mt-1 text-xs">{{ $order->created_at->format('h:i A') }}</p></td>
                                        <td class="px-6 py-4"><div class="flex items-center justify-end gap-2"><a href="{{ route('orders.show', $order) }}" title="View order" class="grid h-8 w-8 place-items-center rounded-full bg-slate-200 text-slate-700 transition hover:bg-blue-500 hover:text-white dark:bg-slate-700 dark:text-slate-200"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="2.5" stroke-width="2"/></svg></a><a href="{{ route('orders.edit', $order) }}" title="Edit order" class="grid h-8 w-8 place-items-center rounded-full bg-slate-200 text-slate-700 transition hover:bg-amber-500 hover:text-white dark:bg-slate-700 dark:text-slate-200"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-width="2" d="m4 20 4.2-1 9.6-9.6a2.1 2.1 0 0 0-3-3L5.2 16 4 20Z"/></svg></a><form method="POST" action="{{ route('orders.destroy', $order) }}" onsubmit="return confirm('Delete this order?');">@csrf @method('DELETE')<button type="submit" title="Delete order" class="grid h-8 w-8 place-items-center rounded-full bg-slate-200 text-slate-700 transition hover:bg-rose-500 hover:text-white dark:bg-slate-700 dark:text-slate-200"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-width="2" d="M6 7h12m-8 4v5m4-5v5M9 7l1-3h4l1 3m-8 0 1 13h8l1-13"/></svg></button></form></div></td>
                                    </tr>
                                @empty
                                    <tr><td colspan="9" class="px-6 py-14 text-center text-slate-500">No orders have been placed yet.</td></tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                    <div x-cloak x-show="view === 'grid'" class="grid gap-4 bg-slate-50/60 p-4 dark:bg-slate-900/20 sm:grid-cols-2 xl:grid-cols-3 sm:p-5">
                        @forelse ($orders as $order)
                            @php
                                $statusClass = match ($order->status) {
                                    'completed' => 'bg-emerald-50 text-emerald-700 ring-emerald-200 dark:bg-emerald-500/15 dark:text-emerald-300',
                                    'confirmed', 'processing' => 'bg-sky-50 text-sky-700 ring-sky-200 dark:bg-sky-500/15 dark:text-sky-300',
                                    'shipped' => 'bg-violet-50 text-violet-700 ring-violet-200 dark:bg-violet-500/15 dark:text-violet-300',
                                    'cancelled' => 'bg-rose-50 text-rose-700 ring-rose-200 dark:bg-rose-500/15 dark:text-rose-300',
                                    default => 'bg-amber-50 text-amber-700 ring-amber-200 dark:bg-amber-500/15 dark:text-amber-300',
                                };
                                $gridDeliveryArea = (App\Services\DeliveryCharges::AREAS[$order->delivery_area] ?? match ((int) $order->shipping_cost) { 50 => 'Dhaka City', 80 => 'Outside Dhaka City', 100 => 'Outside Dhaka District', default => 'Delivery' });
                            @endphp
                            <article class="flex flex-col rounded-2xl border bg-white p-4 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md dark:bg-[#161f2e] {{ $order->viewed_at ? 'border-slate-200 dark:border-slate-700' : 'border-indigo-300 ring-2 ring-indigo-100 dark:border-indigo-500/50 dark:ring-indigo-500/10' }}">
                                <div class="flex items-start justify-between gap-3"><div class="flex min-w-0 items-center gap-3"><span class="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-gradient-to-br from-sky-100 to-teal-100 text-sm font-bold text-sky-700 dark:from-sky-500/20 dark:to-teal-500/20 dark:text-sky-300">{{ strtoupper(substr($order->customer_name, 0, 1)) }}</span><div class="min-w-0"><h3 class="truncate font-semibold">{{ $order->customer_name }}</h3><p class="mt-0.5 text-xs text-slate-400">{{ $order->created_at->format('M d, Y · h:i A') }}</p></div></div><span class="rounded-full px-2.5 py-1 text-[11px] font-semibold capitalize ring-1 {{ $statusClass }}">{{ str_replace('_', ' ', $order->status) }}</span></div>
                                <div class="mt-3 space-y-1 text-xs text-slate-500"><p class="flex items-center gap-1.5"><svg class="h-3.5 w-3.5 text-sky-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-width="1.8" d="M6 3h3l2 5-2 2c1.5 3 2.5 4 5 5l2-2 5 2v3a3 3 0 0 1-3 3A15 15 0 0 1 3 6a3 3 0 0 1 3-3Z"/></svg>{{ $order->customer_phone }}@if ($order->customer_order_count > 1)<a href="{{ route('orders.index', ['search' => $order->customer_phone]) }}" title="{{ $order->customer_order_count }} orders from this customer" class="ml-1 inline-flex rounded-full bg-violet-50 px-2 py-0.5 text-[10px] font-semibold text-violet-700 hover:bg-violet-100 dark:bg-violet-500/15 dark:text-violet-300">Repeat</a>@endif</p>@if ($order->customer_email)<p class="flex items-center gap-1.5"><svg class="h-3.5 w-3.5 text-indigo-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="14" rx="2" stroke-width="1.8"/><path stroke-width="1.8" d="m4 7 8 6 8-6"/></svg>{{ $order->customer_email }}</p>@endif</div>
                                <div class="mt-4 flex items-center justify-between border-y border-dashed border-slate-200 py-3 text-[11px] uppercase tracking-wider text-slate-400 dark:border-slate-700"><span>Order: <a href="{{ route('orders.show', $order) }}" class="font-bold text-indigo-600 hover:underline dark:text-indigo-400">{{ $order->order_number }}</a></span><span>Items: <b class="text-slate-700 dark:text-slate-200">{{ $order->items->sum('quantity') }}</b></span></div>
                                <div class="my-4 space-y-2.5 text-sm">@foreach ($order->items as $item)<div class="flex gap-3"><span class="w-5 shrink-0 text-xs text-slate-400">{{ $item->quantity }}</span><span class="min-w-0 flex-1">@if ($item->product)<a href="{{ route('catalog.show', $item->product->slug) }}" class="hover:text-indigo-600 dark:hover:text-indigo-400">{{ $item->product_title }}</a>@else{{ $item->product_title }}@endif</span><span class="whitespace-nowrap text-slate-500">৳{{ number_format((float) $item->line_total, 2) }}</span></div>@endforeach</div>
                                <div class="space-y-2 border-t border-dashed border-slate-200 py-3 text-xs dark:border-slate-700"><p><span class="font-semibold text-sky-700 dark:text-sky-300">{{ $gridDeliveryArea }}</span></p><p class="leading-5 text-slate-500">{{ $order->shipping_address }}</p>@if ($order->customer_note)<p class="rounded-lg bg-amber-50 px-3 py-2 leading-5 text-amber-800 dark:bg-amber-500/10 dark:text-amber-300"><span class="font-semibold">অর্ডার নোট:</span> {{ $order->customer_note }}</p>@endif</div>
                                <div class="mt-auto space-y-1.5 border-t border-dashed border-slate-200 pt-3 text-xs dark:border-slate-700"><div class="flex justify-between text-slate-500"><span>Products</span><span>৳{{ number_format((float) $order->subtotal, 2) }}</span></div><div class="flex items-center justify-between gap-4 text-slate-500"><span class="flex items-center gap-1.5 rounded-lg bg-sky-50 px-2 py-1 font-semibold text-sky-700 ring-1 ring-inset ring-sky-100 dark:bg-sky-500/10 dark:text-sky-300 dark:ring-sky-500/20"><svg class="h-3.5 w-3.5 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="M3 7h11v10H3V7Zm11 3h3l4 4v3h-7v-7Zm-7 9a2 2 0 1 0 0-4 2 2 0 0 0 0 4Zm10 0a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z"/></svg>{{ $gridDeliveryArea }}</span><span>৳{{ number_format((float) $order->shipping_cost, 2) }}</span></div><div class="flex justify-between pt-1 text-base font-bold"><span>Total</span><span>৳{{ number_format((float) $order->total, 2) }}</span></div></div>
                                <div class="mt-4 grid grid-cols-[1fr_1fr_auto] gap-2"><a href="{{ route('orders.show', $order) }}" class="rounded-lg border border-slate-200 px-3 py-2 text-center text-xs font-semibold transition hover:bg-slate-50 dark:border-slate-700 dark:hover:bg-slate-800">View</a><a href="{{ route('orders.edit', $order) }}" class="rounded-lg bg-slate-900 px-3 py-2 text-center text-xs font-semibold text-white transition hover:bg-slate-700 dark:bg-sky-600 dark:hover:bg-sky-500">Edit</a><form method="POST" action="{{ route('orders.destroy', $order) }}" onsubmit="return confirm('Delete this order?');">@csrf @method('DELETE')<button class="grid h-8 w-9 place-items-center rounded-lg border border-rose-200 text-rose-500 transition hover:bg-rose-50 dark:border-rose-500/30 dark:hover:bg-rose-500/10" title="Delete order"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-width="2" d="M6 7h12m-8 4v5m4-5v5M9 7l1-3h4l1 3m-8 0 1 13h8l1-13"/></svg></button></form></div>
                            </article>
                        @empty
                            <div class="py-14 text-center text-sm text-slate-500 sm:col-span-2 xl:col-span-3">No orders have been placed yet.</div>
                        @endforelse
                    </div>
                    @if ($orders->total() > 0)
                        <nav aria-label="Order pagination" class="flex flex-col gap-4 border-t border-slate-200 px-5 py-4 dark:border-slate-800 sm:flex-row sm:items-center sm:justify-between">
                            <div class="flex flex-wrap items-center gap-1 text-xs font-semibold">
                                @if ($orders->onFirstPage())<span class="px-2 py-2 text-slate-400">PREV</span>@else<a href="{{ $orders->previousPageUrl() }}" class="px-2 py-2 text-slate-700 hover:text-indigo-600 dark:text-slate-300">PREV</a>@endif
                                @php $firstPaginationPage = max(1, $orders->currentPage() - 2); $lastPaginationPage = min($orders->lastPage(), $orders->currentPage() + 2); @endphp
                                @if ($firstPaginationPage > 1)<a href="{{ $orders->url(1) }}" class="grid h-9 min-w-9 place-items-center rounded px-2 transition hover:bg-slate-100 dark:hover:bg-slate-800">1</a>@endif
                                @if ($firstPaginationPage > 2)<span class="px-2 py-2 text-slate-400">…</span>@endif
                                @foreach (range($firstPaginationPage, $lastPaginationPage) as $page)
                                    @if ($page === $orders->currentPage())<span aria-current="page" class="grid h-9 min-w-9 place-items-center rounded-lg bg-indigo-600 px-2 text-white">{{ $page }}</span>@else<a href="{{ $orders->url($page) }}" class="grid h-9 min-w-9 place-items-center rounded-lg px-2 transition hover:bg-slate-100 dark:hover:bg-slate-800">{{ $page }}</a>@endif
                                @endforeach
                                @if ($lastPaginationPage < $orders->lastPage() - 1)<span class="px-2 py-2 text-slate-400">…</span>@endif
                                @if ($lastPaginationPage < $orders->lastPage())<a href="{{ $orders->url($orders->lastPage()) }}" class="grid h-9 min-w-9 place-items-center rounded-lg px-2 transition hover:bg-slate-100 dark:hover:bg-slate-800">{{ $orders->lastPage() }}</a>@endif
                                @if ($orders->hasMorePages())<a href="{{ $orders->nextPageUrl() }}" class="px-2 py-2 text-slate-700 hover:text-indigo-600 dark:text-slate-300">NEXT</a>@else<span class="px-2 py-2 text-slate-400">NEXT</span>@endif
                            </div>
                            <p class="text-xs font-medium text-slate-500">Showing {{ $orders->firstItem() }} to {{ $orders->lastItem() }} of {{ $orders->total() }} ({{ $orders->lastPage() }} {{ Str::plural('Page', $orders->lastPage()) }})</p>
                        </nav>
                    @endif
                    </div>
                </section>
            </div>
        </main>
    </div>
</x-admin-layout>
