<x-admin-layout title="Order {{ $order->order_number }}">
@php
$currentStatus=App\OrderStatus::from($order->status);
$deliveryArea=(App\Services\DeliveryCharges::AREAS[$order->delivery_area] ?? match ((int) $order->shipping_cost) { 50 => 'Dhaka City', 80 => 'Outside Dhaka City', 100 => 'Outside Dhaka District', default => 'Delivery' });
$workflowSteps=[App\OrderStatus::Pending,App\OrderStatus::Confirmed,App\OrderStatus::Processing,App\OrderStatus::ReadyToShip,App\OrderStatus::Shipped,App\OrderStatus::Completed];
$currentStep=collect($workflowSteps)->search(fn($status)=>$status===$currentStatus);
@endphp
<div class="min-h-screen bg-slate-50 text-slate-900 dark:bg-[#111827] dark:text-slate-100">
<div x-cloak x-show="menuOpen" @click="menuOpen=false" class="fixed inset-0 z-30 bg-slate-950/50 lg:hidden"></div><x-admin-sidebar />
<main class="min-w-0 lg:pl-72"><x-admin-topbar /><div class="mx-auto max-w-7xl p-4 sm:p-6 lg:p-8">
<div class="mb-5 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><a href="{{ route('orders.index') }}" class="text-sm font-semibold text-indigo-600 dark:text-indigo-400">← Back to orders</a><div class="flex flex-wrap gap-2"><a href="{{ route('orders.print-label',$order) }}" target="_blank" class="ds-button-primary">Print parcel label</a><a href="{{ route('orders.edit',$order) }}" class="ds-button-secondary">Edit order</a><form method="POST" action="{{ route('orders.destroy',$order) }}" onsubmit="return confirm('Delete this order permanently?')">@csrf @method('DELETE')<button class="ds-button-danger">Delete</button></form></div></div>
@if(session('status'))<div class="mb-5 rounded-xl bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-700 dark:bg-emerald-500/15 dark:text-emerald-300">{{ session('status') }}</div>@endif
@if(session('error'))<div class="mb-5 rounded-xl bg-rose-50 px-4 py-3 text-sm font-medium text-rose-700 dark:bg-rose-500/15 dark:text-rose-300">{{ session('error') }}</div>@endif
<section class="ds-card overflow-hidden"><div class="flex flex-col gap-5 p-5 sm:p-7 lg:flex-row lg:items-center lg:justify-between"><div><div class="flex flex-wrap items-center gap-3"><h1 class="text-2xl font-bold sm:text-3xl">{{ $order->order_number }}</h1><span class="rounded-full bg-indigo-50 px-3 py-1 text-xs font-semibold text-indigo-700 dark:bg-indigo-500/15 dark:text-indigo-300">{{ $currentStatus->label() }}</span></div><p class="mt-2 text-sm text-slate-500">Placed {{ $order->created_at->format('d M Y, h:i A') }}</p></div><div class="grid grid-cols-3 gap-2 text-sm"><div class="rounded-xl border border-slate-200 px-3 py-3 dark:border-slate-700"><p class="text-xs text-slate-500">Customer</p><p class="mt-1 max-w-32 truncate font-semibold">{{ $order->customer_name }}</p></div><div class="rounded-xl border border-slate-200 px-3 py-3 dark:border-slate-700"><p class="text-xs text-slate-500">Items</p><p class="mt-1 font-semibold">{{ $order->items->sum('quantity') }}</p></div><div class="rounded-xl border border-indigo-200 px-3 py-3 text-indigo-700 dark:border-indigo-500/30 dark:text-indigo-300"><p class="text-xs text-indigo-500">Total</p><p class="mt-1 font-bold">৳{{ number_format((float)$order->total,2) }}</p></div></div></div></section>
<div class="mt-5 grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><div class="space-y-5">
<section class="ds-card overflow-hidden"><div class="ds-card-header"><h2 class="ds-section-title">Customer & delivery</h2><p class="ds-section-description">Contact and delivery information in one place.</p></div><div class="grid divide-y divide-slate-100 dark:divide-slate-800 md:grid-cols-2 md:divide-x md:divide-y-0"><div class="p-5 sm:p-6"><div class="flex flex-wrap items-center gap-2"><p class="font-bold">{{ $order->customer_name }}</p>@if($customerOrderCount>1)<a href="{{ route('orders.index',['search'=>$order->customer_phone]) }}" title="{{ $customerOrderCount }} orders from this customer" class="rounded-full bg-violet-50 px-2 py-0.5 text-[10px] font-semibold text-violet-700 dark:bg-violet-500/15 dark:text-violet-300">Repeat · {{ $customerOrderCount }}</a>@endif</div><a href="tel:{{ $order->customer_phone }}" class="mt-2 block text-sm font-medium text-indigo-600 dark:text-indigo-400">{{ $order->customer_phone }}</a>@if($order->customer_email)<a href="mailto:{{ $order->customer_email }}" class="mt-1 block truncate text-sm text-slate-500">{{ $order->customer_email }}</a>@endif</div><div class="p-5 sm:p-6"><span class="rounded-full bg-sky-50 px-2.5 py-1 text-xs font-semibold text-sky-700 dark:bg-sky-500/15 dark:text-sky-300">{{ $deliveryArea }}</span><p class="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{{ $order->shipping_address ?: 'No shipping address — digital order.' }}</p></div></div>@if($order->customer_note)<div class="border-t border-amber-100 bg-amber-50/70 px-5 py-4 text-sm dark:border-amber-500/20 dark:bg-amber-500/10"><p class="text-xs font-bold uppercase tracking-wider text-amber-700 dark:text-amber-300">Customer note</p><p class="mt-1">{{ $order->customer_note }}</p></div>@endif</section>
<section class="ds-card overflow-hidden"><div class="ds-card-header"><h2 class="ds-section-title">Order items</h2><p class="ds-section-description">{{ $order->items->sum('quantity') }} item(s) in this order.</p></div><div class="hidden overflow-x-auto sm:block"><table class="w-full min-w-[620px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-slate-800/60"><tr><th class="px-6 py-3">Product</th><th class="px-6 py-3 text-right">Price</th><th class="px-6 py-3 text-center">Qty</th><th class="px-6 py-3 text-right">Total</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">@foreach($order->items as $item)<tr><td class="px-6 py-4"><p class="font-semibold">{{ $item->product_title }}</p>@if($item->sku)<p class="mt-1 text-xs text-slate-400">SKU: {{ $item->sku }}</p>@endif</td><td class="px-6 py-4 text-right">৳{{ number_format((float)$item->unit_price,2) }}</td><td class="px-6 py-4 text-center"><span class="rounded-lg bg-slate-100 px-2.5 py-1 font-semibold dark:bg-slate-800">{{ $item->quantity }}</span></td><td class="px-6 py-4 text-right font-bold">৳{{ number_format((float)$item->line_total,2) }}</td></tr>@endforeach</tbody></table></div><div class="divide-y divide-slate-100 dark:divide-slate-800 sm:hidden">@foreach($order->items as $item)<div class="flex justify-between gap-4 p-5"><div><p class="font-semibold">{{ $item->product_title }}</p><p class="mt-2 text-xs text-slate-500">৳{{ number_format((float)$item->unit_price,2) }} × {{ $item->quantity }}</p></div><p class="shrink-0 font-bold">৳{{ number_format((float)$item->line_total,2) }}</p></div>@endforeach</div><div class="border-t border-slate-200 bg-slate-50/70 p-5 dark:border-slate-800 dark:bg-slate-800/30 sm:flex sm:justify-end"><dl class="w-full space-y-3 text-sm sm:max-w-sm"><div class="flex justify-between"><dt class="text-slate-500">Subtotal</dt><dd>৳{{ number_format((float)$order->subtotal,2) }}</dd></div><div class="flex justify-between"><dt class="text-slate-500">Delivery charge</dt><dd>৳{{ number_format((float)$order->shipping_cost,2) }}</dd></div><div class="flex justify-between border-t border-slate-200 pt-3 text-lg font-bold dark:border-slate-700"><dt>Grand total</dt><dd class="text-indigo-700 dark:text-indigo-300">৳{{ number_format((float)$order->total,2) }}</dd></div></dl></div></section>
<section class="ds-card overflow-hidden"><div class="ds-card-header"><h2 class="ds-section-title">Status timeline</h2><p class="ds-section-description">Who changed the order and when.</p></div><div class="p-5">@forelse($order->statusHistories as $history)<div class="relative flex gap-4 pb-6 last:pb-0">@if(!$loop->last)<span class="absolute left-[7px] top-5 h-[calc(100%-8px)] w-px bg-slate-200 dark:bg-slate-700"></span>@endif<span class="relative mt-1.5 h-3.5 w-3.5 shrink-0 rounded-full border-2 border-white bg-indigo-500 ring-2 ring-indigo-100 dark:border-slate-900"></span><div><p class="text-sm font-semibold">{{ $history->from_status?App\OrderStatus::from($history->from_status)->label().' → ':'' }}{{ App\OrderStatus::from($history->to_status)->label() }}</p><p class="mt-1 text-xs text-slate-500">{{ $history->user?->name??'System' }} · {{ $history->created_at->format('d M Y, h:i A') }}</p>@if($history->note)<p class="mt-2 rounded-lg bg-slate-50 px-3 py-2 text-sm dark:bg-slate-800/60">{{ $history->note }}</p>@endif</div></div>@empty<p class="py-5 text-center text-sm text-slate-500">No status history recorded.</p>@endforelse</div></section>
</div><aside class="space-y-5 xl:sticky xl:top-6">
<section class="ds-card overflow-hidden"><div class="ds-card-header"><h2 class="ds-section-title">Order progress</h2><p class="ds-section-description">Current stage and valid next actions.</p></div><div class="p-5">
<ol aria-label="Order progress" class="space-y-0">@foreach($workflowSteps as $index=>$step)<li class="relative flex gap-3 pb-4 last:pb-0">@if(!$loop->last)<span class="absolute left-[15px] top-8 h-[calc(100%-16px)] w-0.5 {{ $currentStep!==false&&$index<$currentStep?'bg-emerald-400':'bg-slate-200 dark:bg-slate-700' }}"></span>@endif<span class="relative grid h-8 w-8 shrink-0 place-items-center rounded-full text-xs font-bold {{ $currentStep!==false&&$index<$currentStep?'bg-emerald-500 text-white':($step===$currentStatus?'bg-indigo-600 text-white ring-4 ring-indigo-100 dark:ring-indigo-500/20':'bg-slate-100 text-slate-400 dark:bg-slate-800') }}">{{ $currentStep!==false&&$index<$currentStep?'✓':$index+1 }}</span><div class="pt-1"><p class="text-sm font-semibold {{ $step===$currentStatus?'text-indigo-700 dark:text-indigo-300':($currentStep!==false&&$index<$currentStep?'text-emerald-700 dark:text-emerald-300':'text-slate-500') }}">{{ $step->label() }}</p>@if($step===$currentStatus)<p class="mt-0.5 text-xs text-indigo-500">Current status</p>@endif</div></li>@endforeach</ol>
@if(in_array($currentStatus,[App\OrderStatus::Cancelled,App\OrderStatus::Returned],true))<div class="mt-4 rounded-xl {{ $currentStatus===App\OrderStatus::Cancelled?'bg-rose-50 text-rose-700 dark:bg-rose-500/15 dark:text-rose-300':'bg-orange-50 text-orange-700 dark:bg-orange-500/15 dark:text-orange-300' }} px-4 py-3 text-sm font-bold">Order {{ $currentStatus->label() }}</div>@endif
@if($nextStatuses)<div class="mt-5 border-t border-slate-200 pt-4 dark:border-slate-700"><p class="mb-3 text-xs font-semibold uppercase tracking-wider text-slate-400">Change status</p><div class="flex flex-wrap gap-2">@foreach($nextStatuses as $nextStatus)<form class="min-w-0 flex-1" method="POST" action="{{ route('orders.status.update',$order) }}" onsubmit="return confirm('Change status to {{ $nextStatus->label() }}?')">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $nextStatus->value }}"><button class="w-full whitespace-nowrap justify-center {{ in_array($nextStatus,[App\OrderStatus::Cancelled,App\OrderStatus::Returned],true)?'ds-button-danger':'ds-button-primary' }}">{{ $nextStatus->label() }}</button></form>@endforeach</div></div>@else<p class="mt-4 rounded-xl bg-slate-50 px-4 py-3 text-sm text-slate-500 dark:bg-slate-800/60">This order has reached a final status.</p>@endif
</div></section>
<section class="ds-card overflow-hidden"><div class="ds-card-header"><h2 class="ds-section-title">Courier</h2><p class="ds-section-description">Steadfast delivery information.</p></div><div class="p-5">@if($order->shipment)<p class="font-bold capitalize">{{ $order->shipment->provider }}</p><p class="text-xs capitalize text-slate-500">{{ str_replace('_',' ',$order->shipment->status) }}</p><dl class="mt-4 space-y-3 rounded-xl bg-slate-50 p-4 text-sm dark:bg-slate-800/60"><div class="flex justify-between"><dt class="text-slate-500">Consignment</dt><dd class="font-semibold">{{ $order->shipment->external_id }}</dd></div><div class="flex justify-between gap-3"><dt class="text-slate-500">Tracking</dt><dd class="break-all text-right font-semibold">{{ $order->shipment->tracking_code?:'Not provided' }}</dd></div></dl><form method="POST" action="{{ route('orders.courier.sync',$order) }}" class="mt-4">@csrf<button class="ds-button-secondary w-full justify-center">Sync courier status</button></form>@elseif($order->status===App\OrderStatus::ReadyToShip->value)<p class="rounded-xl bg-violet-50 p-4 text-sm text-violet-700 dark:bg-violet-500/10 dark:text-violet-300">Ready to create a Steadfast parcel.</p><form method="POST" action="{{ route('orders.courier.send',$order) }}" class="mt-4" onsubmit="return confirm('Create this parcel in Steadfast?')">@csrf<button class="ds-button-primary w-full justify-center">Send to Steadfast</button></form>@else<p class="rounded-xl bg-slate-50 p-4 text-sm text-slate-500 dark:bg-slate-800/60">Move the order to <strong>Ready to Ship</strong> before sending it.</p>@endif</div></section>
<section class="ds-card p-5"><p class="text-xs font-semibold uppercase tracking-wider text-slate-400">Payment method</p><p class="mt-2 font-semibold capitalize">{{ str_replace('_',' ',$order->payment_method) }}</p></section>
</aside></div></div></main></div>
</x-admin-layout>
