@php
    $storeRoute = $type === 'income' ? 'income-categories.store' : 'expense-categories.store';
    $updateBaseUrl = url('/accounting/'.$type.'-categories');
    $destroyRoute = $type === 'income' ? 'income-categories.destroy' : 'expense-categories.destroy';
@endphp
<x-admin-layout :title="$title">
    <div x-data="{ addOpen: @js($errors->any()), viewing: null, editing: null }" class="ds-page">
        <div x-cloak x-show="menuOpen" @click="menuOpen=false" class="fixed inset-0 z-30 bg-slate-950/50 lg:hidden"></div>
        <x-admin-sidebar />
        <main class="min-w-0 lg:pl-72"><x-admin-topbar />
            <div class="mx-auto max-w-7xl p-5 sm:p-8">
                <div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
                    <div><p class="text-sm font-semibold text-indigo-600">Accounting</p><h1 class="mt-1 text-2xl font-bold">{{ $title }}</h1><p class="mt-2 text-sm text-slate-500">Manage reusable {{ $type }} categories.</p></div>
                    <button type="button" @click="addOpen=true" class="ds-button-primary"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-width="2" d="M12 5v14M5 12h14"/></svg>Add Category</button>
                </div>
                @if(session('status'))<div class="mb-6 rounded-xl bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-700">{{ session('status') }}</div>@endif
                <section class="ds-card overflow-hidden">
                    <div class="overflow-x-auto"><table class="w-full min-w-[680px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-slate-800/60"><tr><th class="px-6 py-4">Category</th><th class="px-6 py-4">Description</th><th class="px-6 py-4">Status</th><th class="px-6 py-4 text-right">Actions</th></tr></thead>
                        <tbody class="divide-y divide-slate-100 dark:divide-slate-800">@forelse($categories as $category)<tr class="transition hover:bg-slate-50/70 dark:hover:bg-slate-800/30"><td class="px-6 py-4 font-semibold">{{ $category->name }}</td><td class="px-6 py-4 text-slate-500">{{ $category->description ?: 'Not provided' }}</td><td class="px-6 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $category->is_active ? 'bg-emerald-50 text-emerald-700 dark:bg-emerald-500/15 dark:text-emerald-300' : 'bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300' }}">{{ $category->is_active ? 'Active' : 'Inactive' }}</span></td><td class="px-6 py-4"><div class="flex justify-end gap-2"><button type="button" @click="viewing=@js($category)" title="View category" aria-label="View category" class="grid h-8 w-8 place-items-center rounded-full bg-slate-200 text-slate-700 transition hover:bg-blue-500 hover:text-white dark:bg-slate-700 dark:text-slate-200"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-width="2" d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="2.5" stroke-width="2"/></svg></button><button type="button" @click="editing=@js($category)" title="Edit category" aria-label="Edit category" class="grid h-8 w-8 place-items-center rounded-full bg-slate-200 text-slate-700 transition hover:bg-amber-500 hover:text-white dark:bg-slate-700 dark:text-slate-200"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-width="2" d="m4 20 4.2-1 9.6-9.6a2.1 2.1 0 0 0-3-3L5.2 16 4 20Z"/></svg></button><form method="POST" action="{{ route($destroyRoute, $category) }}" onsubmit="return confirm('Delete this category?')">@csrf @method('DELETE')<button type="submit" title="Delete category" aria-label="Delete category" class="grid h-8 w-8 place-items-center rounded-full bg-slate-200 text-slate-700 transition hover:bg-rose-500 hover:text-white dark:bg-slate-700 dark:text-slate-200"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-width="2" d="M6 7h12m-8 4v5m4-5v5M9 7l1-3h4l1 3m-8 0 1 13h8l1-13"/></svg></button></form></div></td></tr>@empty<tr><td colspan="4" class="px-6 py-14 text-center text-slate-500">No categories found.</td></tr>@endforelse</tbody>
                    </table></div>@if($categories->hasPages())<div class="border-t p-4">{{ $categories->links() }}</div>@endif
                </section>
            </div>
        </main>
        <div x-cloak x-show="viewing" x-transition.opacity @keydown.escape.window="viewing=null" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div role="dialog" aria-modal="true" @click.outside="viewing=null" class="ds-card w-full max-w-lg overflow-hidden shadow-2xl"><div class="flex items-center justify-between border-b border-slate-200 bg-slate-50 px-6 py-4 dark:border-slate-700 dark:bg-slate-800/60"><div><p class="text-xs font-semibold uppercase tracking-wider text-indigo-600">{{ ucfirst($type) }} category</p><h2 class="mt-1 text-xl font-bold" x-text="viewing?.name"></h2></div><x-modal-close-button @click="viewing=null" /></div><div class="space-y-5 p-6"><div><p class="text-xs font-semibold uppercase tracking-wider text-slate-400">Description</p><p class="mt-2 text-sm text-slate-600 dark:text-slate-300" x-text="viewing?.description || 'No description added.'"></p></div><div><p class="text-xs font-semibold uppercase tracking-wider text-slate-400">Status</p><span class="mt-2 inline-flex rounded-full px-2.5 py-1 text-xs font-semibold" :class="viewing?.is_active ? 'bg-emerald-50 text-emerald-700 dark:bg-emerald-500/15 dark:text-emerald-300' : 'bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300'" x-text="viewing?.is_active ? 'Active' : 'Inactive'"></span></div></div><div class="flex justify-end border-t border-slate-200 px-6 py-4 dark:border-slate-700"><button type="button" @click="viewing=null" class="ds-button-secondary">Close</button></div></div></div>
        <div x-cloak x-show="addOpen" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div @click.outside="addOpen=false" class="ds-card w-full max-w-lg p-6 shadow-2xl"><h2 class="text-xl font-bold">Add {{ ucfirst($type) }} Category</h2><form method="POST" action="{{ route($storeRoute) }}" class="mt-5 space-y-4">@csrf
            <div><label class="text-sm font-semibold">Category name</label><input name="name" value="{{ old('name') }}" required class="ds-input ds-control">@error('name')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div>
            <div><label class="text-sm font-semibold">Description</label><textarea name="description" rows="3" class="ds-input ds-control">{{ old('description') }}</textarea></div>
            <label class="flex gap-2"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" checked> Active</label>
            <div class="flex justify-end gap-2"><button type="button" @click="addOpen=false" class="ds-button-secondary">Cancel</button><button class="ds-button-primary">Save</button></div>
        </form></div></div>
        <div x-cloak x-show="editing" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div @click.outside="editing=null" class="ds-card w-full max-w-lg p-6 shadow-2xl"><h2 class="text-xl font-bold">Edit Category</h2><form data-ds-dirty-submit method="POST" :action="`{{ $updateBaseUrl }}/${editing?.id}`" class="mt-5 space-y-4">@csrf @method('PUT')
            <input name="name" x-model="editing.name" required class="ds-input"><textarea name="description" x-model="editing.description" rows="3" class="ds-input"></textarea>
            <label class="flex gap-2"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" x-model="editing.is_active"> Active</label>
            <div class="flex justify-end gap-2"><button type="button" @click="editing=null" class="ds-button-secondary">Cancel</button><button class="ds-button-primary">Update</button></div>
        </form></div></div>
    </div>
</x-admin-layout>
