@php
    $storeRoute = $type === 'income' ? 'incomes.store' : 'expenses.store';
    $destroyRoute = $type === 'income' ? 'incomes.destroy' : 'expenses.destroy';
    $updateBaseUrl = url('/accounting/'.$type.'s');
    $categoryRoute = $type === 'income' ? 'accounting.income-categories' : 'accounting.expense-categories';
    $oldItems = old('items', [['category_id' => '', 'amount' => '']]);
@endphp
<x-admin-layout :title="$title">
<div x-data="{ addOpen:@js($errors->any()), viewing:null, editing:null, addItems:@js($oldItems), row(){return {category_id:'',amount:''}}, total(rows){return rows.reduce((sum,row)=>sum+(parseFloat(row.amount)||0),0).toFixed(2)}, edit(entry){this.editing={...entry,entry_date:entry.entry_date.substring(0,10),items:entry.items.map(item=>({category_id:item.{{ $type }}_category_id,amount:item.amount}))}} }" class="ds-page">
    <div x-cloak x-show="menuOpen" @click="menuOpen=false" class="fixed inset-0 z-30 bg-slate-950/50 lg:hidden"></div><x-admin-sidebar />
    <main class="min-w-0 lg:pl-72"><x-admin-topbar /><div class="mx-auto max-w-7xl p-5 sm:p-8">
        <div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold text-indigo-600">Accounting</p><h1 class="text-2xl font-bold">{{ $title }}</h1><p class="mt-2 text-sm text-slate-500">Record and manage {{ $type }} entries.</p></div><button type="button" @click="addOpen=true" @disabled($categories->isEmpty()) class="ds-button-primary"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-width="2" d="M12 5v14M5 12h14"/></svg>Add {{ $title }}</button></div>
        @if($categories->isEmpty())<div class="mb-5 rounded-xl bg-amber-50 p-4 text-sm text-amber-800">Create an active category first. <a class="font-bold underline" href="{{ route($categoryRoute) }}">Manage categories</a></div>@endif
        @if(session('status'))<div class="mb-5 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">{{ session('status') }}</div>@endif
        <section class="ds-card overflow-hidden"><div class="overflow-x-auto"><table class="w-full min-w-[800px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-slate-800/60"><tr><th class="px-5 py-4">Date</th><th class="px-5 py-4">Categories</th><th class="px-5 py-4">Remarks</th><th class="px-5 py-4 text-right">Total</th><th class="px-5 py-4 text-right">Actions</th></tr></thead><tbody class="divide-y dark:divide-slate-800">
        @forelse($entries as $entry)<tr><td class="px-5 py-4">{{ $entry->entry_date->format('d M Y') }}</td><td class="px-5 py-4">@foreach($entry->items as $item)<div>{{ $item->category_name }} &mdash; {{ number_format((float)$item->amount,2) }}</div>@endforeach</td><td class="px-5 py-4 text-slate-500">{{ $entry->remarks ?: 'Not provided' }}</td><td class="px-5 py-4 text-right font-bold">{{ number_format((float)$entry->total_amount,2) }}</td><td class="px-5 py-4"><div class="flex justify-end gap-2"><button type="button" @click="viewing=@js($entry)" title="View {{ $type }}" aria-label="View {{ $type }}" class="grid h-8 w-8 place-items-center rounded-full bg-slate-200 text-slate-700 transition hover:bg-blue-500 hover:text-white dark:bg-slate-700 dark:text-slate-200"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-width="2" d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="2.5" stroke-width="2"/></svg></button><button type="button" @click="edit(@js($entry))" title="Edit {{ $type }}" aria-label="Edit {{ $type }}" class="grid h-8 w-8 place-items-center rounded-full bg-slate-200 text-slate-700 transition hover:bg-amber-500 hover:text-white dark:bg-slate-700 dark:text-slate-200"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-width="2" d="m4 20 4.2-1 9.6-9.6a2.1 2.1 0 0 0-3-3L5.2 16 4 20Z"/></svg></button><form method="POST" action="{{ route($destroyRoute,$entry) }}" onsubmit="return confirm('Delete this entry?')">@csrf @method('DELETE')<button type="submit" title="Delete {{ $type }}" aria-label="Delete {{ $type }}" class="grid h-8 w-8 place-items-center rounded-full bg-slate-200 text-slate-700 transition hover:bg-rose-500 hover:text-white dark:bg-slate-700 dark:text-slate-200"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-width="2" d="M6 7h12m-8 4v5m4-5v5M9 7l1-3h4l1 3m-8 0 1 13h8l1-13"/></svg></button></form></div></td></tr>@empty<tr><td colspan="5" class="px-5 py-14 text-center text-slate-500">No {{ $type }} entries found.</td></tr>@endforelse
        </tbody></table></div>@if($entries->hasPages())<div class="border-t p-4">{{ $entries->links() }}</div>@endif</section>
    </div></main>
    <div x-cloak x-show="viewing" x-transition.opacity @keydown.escape.window="viewing=null" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div role="dialog" aria-modal="true" @click.outside="viewing=null" class="ds-card w-full max-w-2xl overflow-hidden shadow-2xl"><div class="flex items-center justify-between border-b border-slate-200 bg-slate-50 px-6 py-4 dark:border-slate-700 dark:bg-slate-800/60"><div><p class="text-xs font-semibold uppercase tracking-wider text-indigo-600">Accounting entry</p><h2 class="mt-1 text-xl font-bold">View {{ $title }}</h2></div><x-modal-close-button @click="viewing=null" /></div><div class="space-y-6 p-6"><div class="grid gap-4 sm:grid-cols-3"><div><p class="text-xs font-semibold uppercase tracking-wider text-slate-400">Date</p><p class="mt-2 font-semibold" x-text="viewing?.entry_date?.substring(0,10)"></p></div><div class="sm:col-span-2"><p class="text-xs font-semibold uppercase tracking-wider text-slate-400">Remarks</p><p class="mt-2 text-sm text-slate-600 dark:text-slate-300" x-text="viewing?.remarks || 'No remarks added.'"></p></div></div><div><p class="mb-3 text-xs font-semibold uppercase tracking-wider text-slate-400">Breakdown</p><div class="overflow-hidden rounded-xl border border-slate-200 dark:border-slate-700"><template x-for="item in viewing?.items || []" :key="item.id"><div class="flex items-center justify-between gap-4 border-b border-slate-100 px-4 py-3 last:border-0 dark:border-slate-700"><span class="font-medium" x-text="item.category_name"></span><span class="font-semibold tabular-nums" x-text="Number(item.amount).toFixed(2)"></span></div></template></div></div><div class="flex items-center justify-between rounded-xl bg-indigo-50 px-4 py-3 text-indigo-700 dark:bg-indigo-500/15 dark:text-indigo-300"><span class="font-semibold">Total amount</span><span class="text-lg font-bold tabular-nums" x-text="Number(viewing?.total_amount || 0).toFixed(2)"></span></div></div><div class="flex justify-end border-t border-slate-200 px-6 py-4 dark:border-slate-700"><button type="button" @click="viewing=null" class="ds-button-secondary">Close</button></div></div></div>
    <div x-cloak x-show="addOpen" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div @click.outside="addOpen=false" class="ds-card max-h-[90vh] w-full max-w-2xl overflow-y-auto p-6 shadow-2xl"><h2 class="text-xl font-bold">Add {{ $title }}</h2><form method="POST" action="{{ route($storeRoute) }}" class="mt-5 space-y-4">@csrf
        <div class="grid gap-4 sm:grid-cols-2"><div><label class="text-sm font-semibold">Date</label><input type="date" name="entry_date" value="{{ old('entry_date',now()->format('Y-m-d')) }}" required class="ds-input ds-control"></div><div><label class="text-sm font-semibold">Remarks</label><input name="remarks" value="{{ old('remarks') }}" class="ds-input ds-control"></div></div>
        <template x-for="(item,index) in addItems" :key="index"><div class="grid grid-cols-[1fr_1fr_auto] gap-3"><select x-model="item.category_id" :name="`items[${index}][category_id]`" required class="ds-input"><option value="">Select category</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select><input type="number" min="0.01" step="0.01" x-model="item.amount" :name="`items[${index}][amount]`" placeholder="Amount" required class="ds-input"><button type="button" @click="addItems.splice(index,1)" x-show="addItems.length>1" class="text-rose-600">Remove</button></div></template>
        @error('items.*')<p class="text-xs text-rose-600">{{ $message }}</p>@enderror<button type="button" @click="addItems.push(row())" class="text-sm font-bold text-indigo-600">+ Add another category</button><div class="text-right text-lg font-bold">Total: <span x-text="total(addItems)"></span></div><div class="flex justify-end gap-2"><button type="button" @click="addOpen=false" class="ds-button-secondary">Cancel</button><button class="ds-button-primary">Save</button></div>
    </form></div></div>
    <div x-cloak x-show="editing" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div @click.outside="editing=null" class="ds-card max-h-[90vh] w-full max-w-2xl overflow-y-auto p-6 shadow-2xl"><h2 class="text-xl font-bold">Edit {{ $title }}</h2><form data-ds-dirty-submit method="POST" :action="`{{ $updateBaseUrl }}/${editing?.id}`" class="mt-5 space-y-4">@csrf @method('PUT')
        <div class="grid gap-4 sm:grid-cols-2"><input type="date" name="entry_date" x-model="editing.entry_date" required class="ds-input"><input name="remarks" x-model="editing.remarks" placeholder="Remarks" class="ds-input"></div>
        <template x-for="(item,index) in editing?.items || []" :key="index"><div class="grid grid-cols-[1fr_1fr_auto] gap-3"><select x-model="item.category_id" :name="`items[${index}][category_id]`" required class="ds-input">@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select><input type="number" min="0.01" step="0.01" x-model="item.amount" :name="`items[${index}][amount]`" required class="ds-input"><button type="button" @click="editing.items.splice(index,1)" x-show="editing.items.length>1" class="text-rose-600">Remove</button></div></template>
        <button type="button" @click="editing.items.push(row())" class="text-sm font-bold text-indigo-600">+ Add another category</button><div class="text-right text-lg font-bold">Total: <span x-text="total(editing?.items || [])"></span></div><div class="flex justify-end gap-2"><button type="button" @click="editing=null" class="ds-button-secondary">Cancel</button><button class="ds-button-primary">Update</button></div>
    </form></div></div>
</div>
</x-admin-layout>
