<x-admin-layout title="Expense Categories">
    <div x-data="{ addCategoryOpen: @js($errors->any()), editingCategory: null }" class="min-h-screen bg-slate-50 text-slate-900 dark:bg-[#111827] dark:text-slate-100">
        <div x-cloak x-show="menuOpen" @click="menuOpen = false" class="fixed inset-0 z-30 bg-slate-950/50 lg:hidden"></div>
        <x-admin-sidebar />

        <main class="min-w-0 lg:pl-72">
            <x-admin-topbar />
            <div class="mx-auto max-w-7xl p-5 sm:p-8">
                <div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
                    <div><p class="text-sm font-semibold text-indigo-600 dark:text-indigo-400">Accounting</p><h1 class="mt-1 text-2xl font-bold">Expense Categories</h1><p class="mt-2 text-sm text-slate-500 dark:text-slate-400">Organize business expenses into reusable categories.</p></div>
                    <button type="button" @click="addCategoryOpen = true" class="inline-flex items-center justify-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-indigo-500/20 transition hover:bg-indigo-700"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-width="2" d="M12 5v14M5 12h14"/></svg>Add Category</button>
                </div>

                @if (session('status'))<div class="mb-6 rounded-xl bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-700 dark:bg-emerald-500/15 dark:text-emerald-300">{{ session('status') }}</div>@endif

                <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-[#161f2e]">
                    <div class="border-b border-slate-200 p-5 dark:border-slate-800"><h2 class="font-bold">All categories</h2><p class="mt-1 text-xs text-slate-500">{{ $categories->total() }} expense {{ Str::plural('category', $categories->total()) }}</p></div>
                    <div class="overflow-x-auto"><table class="w-full min-w-[680px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wider text-slate-500 dark:bg-slate-800/60 dark:text-slate-400"><tr><th class="px-6 py-4">Category</th><th class="px-6 py-4">Description</th><th class="px-6 py-4">Status</th><th class="px-6 py-4">Created</th><th class="px-6 py-4 text-right">Actions</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">
                        @forelse ($categories as $category)
                            <tr class="transition hover:bg-slate-50/70 dark:hover:bg-slate-800/30"><td class="px-6 py-4 font-semibold">{{ $category->name }}</td><td class="max-w-md px-6 py-4 text-slate-500 dark:text-slate-400">{{ $category->description ?: '—' }}</td><td class="px-6 py-4">@if ($category->is_active)<span class="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700 dark:bg-emerald-500/15 dark:text-emerald-300">Active</span>@else<span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-600 dark:bg-slate-800 dark:text-slate-300">Inactive</span>@endif</td><td class="px-6 py-4 text-slate-500 dark:text-slate-400">{{ $category->created_at->format('M d, Y') }}</td><td class="px-6 py-4"><div class="flex items-center justify-end gap-2"><button type="button" @click="editingCategory = @js($category)" class="rounded-lg bg-indigo-50 px-3 py-2 text-xs font-semibold text-indigo-700 dark:bg-indigo-500/15 dark:text-indigo-300">Edit</button><form method="POST" action="{{ route('expense-categories.destroy', $category) }}" onsubmit="return confirm('Delete this expense category?');">@csrf @method('DELETE')<button type="submit" class="rounded-lg bg-rose-50 px-3 py-2 text-xs font-semibold text-rose-700 dark:bg-rose-500/15 dark:text-rose-300">Delete</button></form></div></td></tr>
                        @empty
                            <tr><td colspan="5" class="px-6 py-14 text-center"><p class="font-semibold">No expense categories found.</p><p class="mt-1 text-sm text-slate-500">Add your first category to organize expenses.</p></td></tr>
                        @endforelse
                    </tbody></table></div>
                    @if ($categories->hasPages())<div class="border-t border-slate-200 px-5 py-4 dark:border-slate-800">{{ $categories->links() }}</div>@endif
                </section>
            </div>
        </main>

        <div x-cloak x-show="addCategoryOpen" x-transition.opacity @keydown.escape.window="addCategoryOpen = false" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div role="dialog" aria-modal="true" @click.outside="addCategoryOpen = false" class="w-full max-w-lg overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl dark:border-slate-700 dark:bg-[#161f2e]"><div class="border-b border-indigo-100 bg-indigo-50 px-5 py-4 dark:border-indigo-500/20 dark:bg-indigo-500/10"><h2 class="text-xl font-bold">Add Expense Category</h2></div><form method="POST" action="{{ route('expense-categories.store') }}">@csrf<div class="space-y-5 p-5 sm:p-7"><div><label for="name" class="text-sm font-semibold">Category name</label><input id="name" name="name" value="{{ old('name') }}" required class="mt-2 w-full rounded-xl border-slate-300 bg-white px-3 py-2.5 text-sm dark:border-slate-700 dark:bg-slate-800">@error('name')<p class="mt-2 text-xs text-rose-600">{{ $message }}</p>@enderror</div><div><label for="description" class="text-sm font-semibold">Description <span class="font-normal text-slate-400">(optional)</span></label><textarea id="description" name="description" rows="3" class="mt-2 w-full rounded-xl border-slate-300 bg-white px-3 py-2.5 text-sm dark:border-slate-700 dark:bg-slate-800">{{ old('description') }}</textarea>@error('description')<p class="mt-2 text-xs text-rose-600">{{ $message }}</p>@enderror</div><label class="flex items-center gap-3"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', '1') === '1') class="rounded border-slate-300 text-indigo-600"><span class="text-sm font-semibold">Active category</span></label></div><div class="flex justify-end gap-3 border-t border-slate-200 px-5 py-4 dark:border-slate-700"><button type="button" @click="addCategoryOpen = false" class="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold dark:border-slate-700">Cancel</button><button type="submit" class="rounded-xl bg-indigo-600 px-5 py-2.5 text-sm font-semibold text-white">Save Category</button></div></form></div></div>

        <div x-cloak x-show="editingCategory" x-transition.opacity @keydown.escape.window="editingCategory = null" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div role="dialog" aria-modal="true" @click.outside="editingCategory = null" class="w-full max-w-lg overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl dark:border-slate-700 dark:bg-[#161f2e]"><div class="border-b border-indigo-100 bg-indigo-50 px-5 py-4 dark:border-indigo-500/20 dark:bg-indigo-500/10"><h2 class="text-xl font-bold">Edit Expense Category</h2></div><form data-ds-dirty-submit method="POST" :action="`{{ url('/accounting/expense-categories') }}/${editingCategory?.id}`">@csrf @method('PUT')<div class="space-y-5 p-5 sm:p-7"><div><label for="edit_name" class="text-sm font-semibold">Category name</label><input id="edit_name" name="name" x-model="editingCategory.name" required class="mt-2 w-full rounded-xl border-slate-300 bg-white px-3 py-2.5 text-sm dark:border-slate-700 dark:bg-slate-800"></div><div><label for="edit_description" class="text-sm font-semibold">Description</label><textarea id="edit_description" name="description" x-model="editingCategory.description" rows="3" class="mt-2 w-full rounded-xl border-slate-300 bg-white px-3 py-2.5 text-sm dark:border-slate-700 dark:bg-slate-800"></textarea></div><label class="flex items-center gap-3"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" :checked="editingCategory?.is_active" class="rounded border-slate-300 text-indigo-600"><span class="text-sm font-semibold">Active category</span></label></div><div class="flex justify-end gap-3 border-t border-slate-200 px-5 py-4 dark:border-slate-700"><button type="button" @click="editingCategory = null" class="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold dark:border-slate-700">Cancel</button><button type="submit" class="rounded-xl bg-indigo-600 px-5 py-2.5 text-sm font-semibold text-white">Save Changes</button></div></form></div></div>
    </div>
</x-admin-layout>
